
--代理業者交易明細檔下載

WITH TEMP AS ( 
		SELECT  
	     COALESCE(TG.TRANSACTIONDATETIME,'') AS TRANSACTIONDATETIME
	    , COALESCE(TG.SEQ , '') AS  SEQ    ,  COALESCE(TG.STAN , '') AS  STAN   
        , COALESCE(TG.PCODE , '') AS  PCODE   , COALESCE(TG.TXID,'') AS TXID
        , COALESCE(TG.TRANSACTIONAMOUNT,'0') AS TRANSACTIONAMOUNT 
	    , TG.AGENT_COMPANY_ID ,   COALESCE(TG.RECEIVERID ,'') RECEIVERID --TG.SND_COMPANY_ID 
        , COALESCE(TG.INBANKID,'') AS INBANKID , COALESCE(TG.OUTBANKID,'') AS OUTBANKID 
        , COALESCE(TG.INNATIONALID,'') INNATIONALID , COALESCE(TG.OUTNATIONALID,'') OUTNATIONALID
	    , COALESCE(TG.INACCOUNTNUM ,'') AS INACCOUNTNUM  , COALESCE(TG.OUTACCOUNTNUM ,'') AS OUTACCOUNTNUM 
        , COALESCE(TG.USERNUM , '') USERNUM, COALESCE(TG.NOTE,'')	NOTE 
        , COALESCE(TG.ISSUERREMARK,'') ISSUERREMARK , COALESCE (TG.HANDLECHARGE,'') HANDLECHARGE   
	    ,( CASE WHEN COALESCE(TG.TG_RESULT ,'') = 'A'  THEN 'A'  ELSE  'R' END) TG_RESULT  	  
        ,COALESCE(TG.BIZDATE , '' ) AS  BIZDATE , COALESCE(TG.CLEARINGPHASE  , '') AS  CLEARINGPHASE 

	    FROM VW_RP_TXNLOG TG 
	    LEFT JOIN ONBLOCKTAB OB ON TG.BIZDATE = OB.BIZDATE AND TG.STAN = OB.STAN   
  
	) 
	SELECT * FROM TEMP 
	

--代理業者交易日統計資料檔下載
WITH TEMP AS(
SELECT * FROM RP_DAILY_TXNLOG 
WHERE BIZDATE >= '20151120' AND BIZDATE <='20151130' AND AGENT_COMPANY_ID = '11111111'
)
,TEMP2 AS (
SELECT BIZDATE ,CLEARINGPHASE , AGENT_COMPANY_ID,SND_COMPANY_ID,PCODE,TXID,TG_RESULT,SUM(CNT) CNT,SUM(AMT) AMT
 FROM TEMP  
GROUP BY BIZDATE ,CLEARINGPHASE ,AGENT_COMPANY_ID,SND_COMPANY_ID,TXID,PCODE,TG_RESULT
)
SELECT  T2.* 
,COALESCE ((SELECT EACH_TXN_NAME FROM EACH_TXN_CODE ETC WHERE ETC.EACH_TXN_ID = PCODE),'') AS PCODE_NAME
,COALESCE ((SELECT TXN_NAME FROM TXN_CODE TC WHERE TC.TXN_ID = TXID),'') AS TXN_NAME
,(SELECT SND_COMPANY_NAME FROM TEMP T WHERE T.SND_COMPANY_ID  = SND_COMPANY_ID FETCH FIRST 1 ROWS ONLY)  SND_COMPANY_NAME
FROM TEMP2 T2
ORDER BY AGENT_COMPANY_ID,SND_COMPANY_ID,TXID,PCODE,TG_RESULT DESC

--代理業者手續費日統計資料檔下載
WITH TEMP AS (
SELECT *  FROM RP_DAILY_TXNLOG  
WHERE BIZDATE >= '20151101' AND BIZDATE <= '20151130' AND TG_RESULT = 'A' AND AGENT_COMPANY_ID = '11111111'
)
, TEMP2 AS(
SELECT BIZDATE,CLEARINGPHASE   ,SND_COMPANY_ID  ,TXID,AGENT_FEE, SUM(CNT) CNT ,SUM( SUM_AGENT_FEE) SUM_AGENT_FEE
 FROM TEMP  
GROUP BY BIZDATE,CLEARINGPHASE   ,SND_COMPANY_ID  ,TXID,AGENT_FEE
)
SELECT T2.*  
,(SELECT SND_COMPANY_NAME FROM TEMP T WHERE T.SND_COMPANY_ID  = SND_COMPANY_ID FETCH FIRST 1 ROWS ONLY)  SND_COMPANY_NAME
,(CASE WHEN T2.SUM_AGENT_FEE < 0 THEN '-' ELSE '+' END) FEE_SIGN
FROM TEMP2 T2
ORDER BY BIZDATE,CLEARINGPHASE   ,SND_COMPANY_ID  ,TXID,AGENT_FEE

--代理業者計費檔下載

WITH TEMP AS (
SELECT *  FROM RP_DAILY_TXNLOG  
WHERE YYYYMM = '201511' AND TG_RESULT = 'A'
)
, TEMP2 AS(
SELECT YYYYMM,AGENT_COMPANY_ID  ,AGENT_FEE ,SUM( SUM_AGENT_FEE) SUM_AGENT_FEE
,  '507' AS  FEENO
 FROM TEMP  
GROUP BY YYYYMM,AGENT_COMPANY_ID  ,AGENT_FEE
)
SELECT T2.*  ,COALESCE( (SELECT COMPANY_NO FROM AGENT_PROFILE AP WHERE AP.COMPANY_ID = T2.AGENT_COMPANY_ID) , '' ) AS COMPANY_NO
,(CASE WHEN SUM_AGENT_FEE< 0 THEN '-'ELSE'+' END  ) FEE_SIGN 
, '' AS RETCOL
FROM TEMP2 T2

ORDER BY YYYYMM , COMPANY_NO



--代理業者交易日統計報表&& 代理業者交易月統計報表 差異在WHERE條件
WITH TEMP AS(
SELECT * FROM RP_DAILY_TXNLOG 
--代理業者交易日統計報表
--WHERE BIZDATE >= '20151120' AND BIZDATE <='20151130'
--代理業者交易月統計報表
WHERE YYYYMM = '201511'
)
,TEMP2 AS (
SELECT AGENT_COMPANY_ID,SND_COMPANY_ID,TXID,PCODE,SUM(CNT) CNT,SUM(AMT) AMT,(CASE WHEN TG_RESULT = 'A' THEN '成功' ELSE '失敗' END) AS TG_RESULT FROM TEMP  
GROUP BY AGENT_COMPANY_ID,SND_COMPANY_ID,TXID,PCODE,TG_RESULT
)
SELECT T2.* 
,COALESCE ((SELECT EACH_TXN_NAME FROM EACH_TXN_CODE ETC WHERE ETC.EACH_TXN_ID = PCODE),'') AS PCODE_NAME
,COALESCE ((SELECT TXN_NAME FROM TXN_CODE TC WHERE TC.TXN_ID = TXID),'') AS TXN_NAME
,(SELECT AGENT_COMPANY_ABBR_NAME FROM TEMP T WHERE T.AGENT_COMPANY_ID  = AGENT_COMPANY_ID FETCH FIRST 1 ROWS ONLY)  AGENT_COMPANY_ABBR_NAME
,(SELECT SND_COMPANY_ABBR_NAME FROM TEMP T WHERE T.SND_COMPANY_ID  = SND_COMPANY_ID FETCH FIRST 1 ROWS ONLY)  SND_COMPANY_ABBR_NAME
FROM TEMP2 T2
ORDER BY AGENT_COMPANY_ID,SND_COMPANY_ID,TXID,PCODE,TG_RESULT DESC



--代理業者交易統計表-代理業者別&代理業者交易統計表-交易代號別
WITH TEMP AS(
SELECT AGENT_COMPANY_ID,AGENT_COMPANY_ABBR_NAME,SND_COMPANY_ID, SND_COMPANY_ABBR_NAME,CNT,BIZDATE,CLEARINGPHASE,AGENT_FEE,SUM_AGENT_FEE,AMT
,TXID,COALESCE ((SELECT TXN_NAME FROM TXN_CODE TC WHERE TC.TXN_ID = TXID),'') AS TXN_NAME
,PCODE,(SELECT EACH_TXN_NAME FROM EACH_TXN_CODE ETC WHERE ETC.EACH_TXN_ID = PCODE) AS PCODE_NAME
,(CASE WHEN TG_RESULT = 'A' THEN '成功' ELSE '失敗' END) AS TG_RESULT_CH
,TG_RESULT
 FROM RP_DAILY_TXNLOG  
WHERE BIZDATE = '20151120' 
--代理業者交易統計表-代理業者別
ORDER BY AGENT_COMPANY_ID,SND_COMPANY_ID,TXID 
--代理業者交易統計表-交易代號別
--ORDER BY TXID ,AGENT_COMPANY_ID,SND_COMPANY_ID
),
TEMP2 AS(
SELECT AGENT_COMPANY_ID,SND_COMPANY_ID,BIZDATE,CLEARINGPHASE,TXID,SUM(AMT) AS AMT,SUM(CNT) AS CNT
,(CASE WHEN TG_RESULT = 'A' THEN '成功' ELSE '失敗' END) AS TG_RESULT
 FROM TEMP  
WHERE TG_RESULT = 'A'
GROUP BY  AGENT_COMPANY_ID,SND_COMPANY_ID,BIZDATE,CLEARINGPHASE,TXID,TG_RESULT
)
, TEMP3 AS(
SELECT AGENT_COMPANY_ID,SND_COMPANY_ID,BIZDATE,CLEARINGPHASE,TXID,SUM(AMT) AS AMT,SUM(CNT) AS CNT
,(CASE WHEN TG_RESULT = 'A' THEN '成功' ELSE '失敗' END) AS TG_RESULT

 FROM TEMP  
WHERE TG_RESULT = 'R'
GROUP BY  AGENT_COMPANY_ID,SND_COMPANY_ID,BIZDATE,CLEARINGPHASE,TXID,TG_RESULT
)
, TEMP4 AS (
SELECT COALESCE( T3.AGENT_COMPANY_ID ,T2.AGENT_COMPANY_ID ) AGENT_COMPANY_ID , COALESCE( T3.SND_COMPANY_ID ,T2.SND_COMPANY_ID ) SND_COMPANY_ID,COALESCE( T3.TXID ,T2.TXID ) TXID 
,COALESCE(T2.TG_RESULT , '成功') AS SUC_RESULT , COALESCE( T2.CNT ,0 ) SUC_CNT ,COALESCE( T2.AMT ,0 ) SUC_AMT 
,COALESCE(T3.TG_RESULT , '失敗') AS FAL_RESULT , COALESCE( T3.CNT ,0 ) FAL_CNT ,COALESCE( T3.AMT ,0 ) FAL_AMT 
,(COALESCE( T3.CNT ,0 )+COALESCE( T2.CNT ,0 )) ROW_CNT,(COALESCE( T3.AMT ,0 )+COALESCE( T2.AMT ,0 )) ROW_AMT
FROM  TEMP3 T3
FULL JOIN TEMP2 T2 ON T3.BIZDATE = T2.BIZDATE AND T3.CLEARINGPHASE = T2.CLEARINGPHASE AND T2.TXID = T3.TXID
 AND T2.AGENT_COMPANY_ID = T3.AGENT_COMPANY_ID AND T2.SND_COMPANY_ID = T3.SND_COMPANY_ID 
)
SELECT
COALESCE ((SELECT TXN_NAME FROM TXN_CODE TC WHERE TC.TXN_ID = TXID),'') AS TXN_NAME
--,COALESCE ((SELECT EACH_TXN_NAME FROM EACH_TXN_CODE ETC WHERE ETC.EACH_TXN_ID = PCODE),'') AS PCODE_NAME
,(SELECT AGENT_COMPANY_ABBR_NAME FROM TEMP T WHERE T.AGENT_COMPANY_ID  = AGENT_COMPANY_ID FETCH FIRST 1 ROWS ONLY)  AGENT_COMPANY_ABBR_NAME
,(SELECT SND_COMPANY_ABBR_NAME FROM TEMP T WHERE T.SND_COMPANY_ID  = SND_COMPANY_ID FETCH FIRST 1 ROWS ONLY)  SND_COMPANY_ABBR_NAME
,T4.* 

FROM TEMP4 T4
--代理業者交易統計表-代理業者別
ORDER BY AGENT_COMPANY_ID,TXID,SND_COMPANY_ID
--代理業者交易統計表-交易代號別
--ORDER BY TXID ,AGENT_COMPANY_ID,SND_COMPANY_ID
GO


--代理業者手續費日報表&& 代理業者手續費月報表

WITH TEMP AS (
SELECT *  FROM RP_DAILY_TXNLOG  
--代理業者手續費日報表
WHERE BIZDATE >= '20151101' AND BIZDATE <= '20151130' AND TG_RESULT = 'A'
--代理業者手續費月報表
WHERE YYYYMM = '201511' AND TG_RESULT = 'A'
)
, TEMP2 AS(
SELECT AGENT_COMPANY_ID  ,SND_COMPANY_ID  ,TXID,AGENT_FEE, SUM(CNT) CNT ,SUM( SUM_AGENT_FEE) SUM_AGENT_FEE
 FROM TEMP  
GROUP BY AGENT_COMPANY_ID  ,SND_COMPANY_ID  ,TXID,AGENT_FEE
ORDER BY AGENT_COMPANY_ID  ,SND_COMPANY_ID  ,TXID,AGENT_FEE
)
SELECT T2.*  
,COALESCE ((SELECT TXN_NAME FROM TXN_CODE TC WHERE TC.TXN_ID = TXID ),'') AS TXN_NAME
,(SELECT AGENT_COMPANY_ABBR_NAME FROM TEMP T WHERE T.AGENT_COMPANY_ID  = AGENT_COMPANY_ID FETCH FIRST 1 ROWS ONLY)  AGENT_COMPANY_ABBR_NAME
,(SELECT SND_COMPANY_ABBR_NAME FROM TEMP T WHERE T.SND_COMPANY_ID  = SND_COMPANY_ID FETCH FIRST 1 ROWS ONLY)  SND_COMPANY_ABBR_NAME
FROM TEMP2 T2
