--V2.0
WITH TEMP AS (
    SELECT * FROM RPDAILYSUMTAB WHERE BIZDATE >= '20150301' AND BIZDATE <= '20150327' AND RESULTSTATUS = 'R' AND CLEARINGPHASE = '01' AND OP_TYPE = 'S' 
)

SELECT 
VARCHAR(A.BGBK_ID) AS BGBK_ID, VARCHAR(A.PCODE) AS PCODE, VARCHAR(A.RESULTSTATUS) AS RESULTSTATUS,
COALESCE((SELECT SUM(COALESCE(CNT,0)) FROM TEMP WHERE BGBK_ID = A.BGBK_ID AND PCODE = A.PCODE AND RESULTSTATUS = A.RESULTSTATUS AND OP_TYPE = 'S'),0) AS FIRECOUNT,
COALESCE((SELECT SUM(COALESCE(AMT,0)) FROM TEMP WHERE BGBK_ID = A.BGBK_ID AND PCODE = A.PCODE AND RESULTSTATUS = A.RESULTSTATUS AND OP_TYPE = 'S'),0) AS FIREAMT,
COALESCE((SELECT SUM(COALESCE(CNT,0)) FROM TEMP WHERE BGBK_ID = A.BGBK_ID AND PCODE = A.PCODE AND RESULTSTATUS = A.RESULTSTATUS AND OP_TYPE = 'O'),0) AS DEBITCOUNT,
COALESCE((SELECT SUM(COALESCE(AMT,0)) FROM TEMP WHERE BGBK_ID = A.BGBK_ID AND PCODE = A.PCODE AND RESULTSTATUS = A.RESULTSTATUS AND OP_TYPE = 'O'),0) AS DEBITAMT,
COALESCE((SELECT SUM(COALESCE(CNT,0)) FROM TEMP WHERE BGBK_ID = A.BGBK_ID AND PCODE = A.PCODE AND RESULTSTATUS = A.RESULTSTATUS AND OP_TYPE = 'I'),0) AS SAVECOUNT,
COALESCE((SELECT SUM(COALESCE(AMT,0)) FROM TEMP WHERE BGBK_ID = A.BGBK_ID AND PCODE = A.PCODE AND RESULTSTATUS = A.RESULTSTATUS AND OP_TYPE = 'I'),0) AS SAVEAMT 
FROM TEMP AS A
GROUP BY A.BGBK_ID, A.PCODE, A.RESULTSTATUS
ORDER BY A.BGBK_ID, A.PCODE, A.RESULTSTATUS

--V1.0
WITH TEMP AS (
SELECT TXDATE, STAN,TXAMT,SENDERACQUIRE,OUTACQUIRE,INACQUIRE,BIZDATE, CLEARINGPHASE, PCODE, RESULTSTATUS 
	,COALESCE(SENDERHEAD,'') AS SENDERHEAD,COALESCE(OUTHEAD,'') AS OUTHEAD,COALESCE(INHEAD,'') AS INHEAD
    FROM RPONBLOCKTAB
    WHERE  BIZDATE = '20150225'  AND  BIZDATE <= '20150225' 
    -- AND  PCODE = '2101'
    --  AND  (SENDERACQUIRE = '9970018' OR OUTACQUIRE = '9970018' OR INACQUIRE = '9970018')
    -- AND  (SENDERHEAD = '1200000' OR OUTHEAD = '1200000' OR INHEAD = '1200000')
    --AND  CLEARINGPHASE = '02'  AND  NEWRESULT = 'R'
    UNION ALL
    SELECT OTXDATE, OSTAN,  TXAMT, SENDERACQUIRE,OUTACQUIRE,INACQUIRE,BIZDATE, CLEARINGPHASE, PCODE
, CASE RESULTCODE WHEN '01' THEN 'B'  WHEN '00'  THEN 'A1' ELSE 'P1' END RESULTSTATUS
, COALESCE(SENDERHEAD,'') AS SENDERHEAD, COALESCE(OUTHEAD,'') AS OUTHEAD,COALESCE(INHEAD,'') AS INHEAD
    FROM RPONPENDINGTAB
    WHERE  BIZDATE = '20150225' AND  BIZDATE <= '20150225' -- AND  PCODE = '2101'
   -- AND  (SENDERACQUIRE = '9970018' OR OUTACQUIRE = '9970018' OR INACQUIRE = '9970018')
  --  AND  (SENDERHEAD = '1200000' OR OUTHEAD = '1200000' OR INHEAD = '1200000')
   -- AND  CLEARINGPHASE = '02'  AND  RESULTCODE = '01'

)

SELECT
-- B.BUSINESS_TYPE_ID ,B.BUSINESS_TYPE_NAME, -- 如要業務類別需加這段
A.BANKID || '-' || (SELECT COALESCE(BGBK_NAME,'') FROM BANK_GROUP WHERE A.BANKID = BGBK_ID) AS BANKHEAD, A.PCODE AS PCODE, 
(CASE A.RESULTSTATUS WHEN 'A' THEN '成功' WHEN 'R' THEN '失敗' ELSE '未完成' END) AS RESULTSTATUS, 
(SELECT COUNT(*) FROM TEMP AS B WHERE B.SENDERHEAD = A.BANKID AND B.PCODE = A.PCODE AND B.RESULTSTATUS = A.RESULTSTATUS) AS FIRECOUNT, 
COALESCE((SELECT SUM(COALESCE(TXAMT,0)) FROM TEMP AS B WHERE B.SENDERHEAD = A.BANKID AND B.PCODE = A.PCODE AND B.RESULTSTATUS = A.RESULTSTATUS),0) AS FIREAMT, 
(SELECT COUNT(*) FROM TEMP AS B WHERE B.OUTHEAD = A.BANKID AND B.PCODE = A.PCODE AND B.RESULTSTATUS = A.RESULTSTATUS) AS DEBITCOUNT, 
COALESCE((SELECT SUM(COALESCE(TXAMT,0)) FROM TEMP AS B WHERE B.OUTHEAD = A.BANKID AND B.PCODE = A.PCODE AND B.RESULTSTATUS = A.RESULTSTATUS),0) AS DEBITAMT, 
(SELECT COUNT(*) FROM TEMP AS B WHERE B.INHEAD = A.BANKID AND B.PCODE = A.PCODE AND B.RESULTSTATUS = A.RESULTSTATUS) AS SAVECOUNT, 
COALESCE((SELECT SUM(COALESCE(TXAMT,0)) FROM TEMP AS B WHERE B.INHEAD = A.BANKID AND B.PCODE = A.PCODE AND B.RESULTSTATUS = A.RESULTSTATUS),0) AS SAVEAMT
FROM (
        SELECT ROWNUMBER() OVER() AS ROWNUMBER, T.* FROM (
                    SELECT SENDERHEAD AS BANKID, PCODE, RESULTSTATUS  FROM TEMP GROUP BY SENDERHEAD, PCODE, RESULTSTATUS 
                    UNION
                    SELECT OUTHEAD, PCODE,  RESULTSTATUS  FROM TEMP GROUP BY OUTHEAD, PCODE, RESULTSTATUS 
                    UNION
                    SELECT INHEAD, PCODE,  RESULTSTATUS  FROM TEMP GROUP BY INHEAD, PCODE, RESULTSTATUS 
                ) AS T LEFT JOIN BANK_GROUP BG ON T.BANKID = BG.BGBK_ID
                WHERE   RESULTSTATUS = 'R' AND   BG.OPBK_ID = '9970018'-- AND BANKID = '0120000' --AND  PCODE = '2101'
) AS A
--如要業務類別需加這段
--JOIN EACH_TXN_CODE T ON A.PCODE = T.EACH_TXN_ID 
--JOIN BUSINESS_TYPE B ON B.BUSINESS_TYPE_ID = T.BUSINESS_TYPE_ID