-- 無分頁版 20150430 edit by hugo req by 李建利 此張報表所有應付金額都要正向表示 差額才有負號
SELECT coalesce( b.CTBK_ID ,'')  CTBK_ID , coalesce((SELECT BGBK_NAME  FROM BANK_GROUP  WHERE BGBK_ID = b.CTBK_ID )  ,'') CTBGBK_NAME 
, coalesce((SELECT CTBK_ACCT  FROM BANK_GROUP  WHERE BGBK_ID = b.CTBK_ID )  ,'') CTBK_ACCT ,VARCHAR(a.CLEARINGPHASE) CLEARINGPHASE 
, VARCHAR(a.BGBK_ID) BGBK_ID , (select coalesce(bgbk_name,'') from bank_group where bgbk_id=a.BGBK_ID) BGBK_NAME
,SUM(a.RECVCNT) RECVCNT , SUM(a.RECVAMT) RECVAMT , SUM(a.PAYCNT) PAYCNT , abs(SUM(a.PAYAMT )) PAYAMT ,SUM(a.RVSRECVCNT) RVSRECVCNT , SUM(a.RVSRECVAMT) RVSRECVAMT ,SUM(a.RVSPAYCNT) RVSPAYCNT , abs(SUM(a.RVSPAYAMT)) RVSPAYAMT 
,SUM(a.RECVAMT+a.RVSRECVAMT) in_tol, abs(SUM(a.PAYAMT+a.RVSPAYAMT)) out_tol,SUM((a.RECVAMT+a.RVSRECVAMT)+(a.PAYAMT+a.RVSPAYAMT)) dif_tol
FROM EACHUSER.RPONCLEARINGTAB a
RIGHT JOIN BANK_GROUP b ON a.BGBK_ID = b.BGBK_ID and b.BGBK_ID != b.CTBK_ID
WHERE a.BIZDATE = '20150429' --AND b.CTBK_ID = '0060000'
GROUP BY b.CTBK_ID , a.BGBK_ID  ,CLEARINGPHASE 

--分頁版 20150430 edit by hugo req by 李建利 此張報表所有應付金額都要正向表示 差額才有負號
SELECT  *  FROM(
    SELECT  ROWNUMBER() OVER() AS ROWNUMBER, coalesce( b.CTBK_ID ,'')  CTBK_ID , coalesce((SELECT BGBK_NAME  FROM BANK_GROUP  WHERE BGBK_ID = b.CTBK_ID )  ,'') CTBGBK_NAME 
    , coalesce((SELECT CTBK_ACCT  FROM BANK_GROUP  WHERE BGBK_ID = b.CTBK_ID )  ,'') CTBK_ACCT ,VARCHAR(a.CLEARINGPHASE) CLEARINGPHASE 
--    ,SUM(a.RECVCNT) RECVCNT , SUM(a.RECVAMT) RECVAMT ,SUM(a.PAYCNT) PAYCNT , SUM(a.PAYAMT ) PAYAMT ,SUM(a.RVSRECVCNT) RVSRECVCNT , SUM(a.RVSRECVAMT) RVSRECVAMT ,SUM(a.RVSPAYCNT) RVSPAYCNT ,SUM(a.RVSPAYAMT) RVSPAYAMT 
--    ,SUM(a.RECVAMT+a.RVSRECVAMT) in_tol, SUM(a.PAYAMT+a.RVSPAYAMT) out_tol,SUM((a.RECVAMT+a.RVSRECVAMT)+(a.PAYAMT+a.RVSPAYAMT)) dif_tol
    ,SUM(a.RECVCNT) RECVCNT , SUM(a.RECVAMT) RECVAMT ,SUM(a.PAYCNT) PAYCNT , abs(SUM(a.PAYAMT )) PAYAMT ,SUM(a.RVSRECVCNT) RVSRECVCNT , SUM(a.RVSRECVAMT) RVSRECVAMT ,SUM(a.RVSPAYCNT) RVSPAYCNT ,abs(SUM(a.RVSPAYAMT)) RVSPAYAMT 
    ,SUM(a.RECVAMT+a.RVSRECVAMT) in_tol, abs(SUM(a.PAYAMT+a.RVSPAYAMT)) out_tol,SUM((a.RECVAMT+a.RVSRECVAMT)+(a.PAYAMT+a.RVSPAYAMT)) dif_tol
    FROM EACHUSER.RPONCLEARINGTAB a
    LEFT JOIN BANK_GROUP b ON a.BGBK_ID = b.BGBK_ID
    WHERE  a.BIZDATE = '20150317' 
    AND b.CTBK_ID IN( SELECT CTBK_ID FROM BANK_GROUP WHERE CTBK_ID !=  BGBK_ID  ) --全部 
    -- b.CTBK_ID  = '0060000' --單筆
    GROUP BY b.CTBK_ID  ,CLEARINGPHASE
    ORDER BY CLEARINGPHASE ,  b.CTBK_ID
) 
WHERE ROWNUMBER >= 1 AND ROWNUMBER <= 10  

--無分頁版
SELECT coalesce( b.CTBK_ID ,'')  CTBK_ID , coalesce((SELECT BGBK_NAME  FROM BANK_GROUP  WHERE BGBK_ID = b.CTBK_ID )  ,'') CTBGBK_NAME 
, coalesce((SELECT CTBK_ACCT  FROM BANK_GROUP  WHERE BGBK_ID = b.CTBK_ID )  ,'') CTBK_ACCT ,VARCHAR(a.CLEARINGPHASE) CLEARINGPHASE 
,SUM(a.RECVCNT) RECVCNT , SUM(a.RECVAMT) RECVAMT ,SUM(a.PAYCNT) PAYCNT , SUM(a.PAYAMT ) PAYAMT ,SUM(a.RVSRECVCNT) RVSRECVCNT , SUM(a.RVSRECVAMT) RVSRECVAMT ,SUM(a.RVSPAYCNT) RVSPAYCNT ,SUM(a.RVSPAYAMT) RVSPAYAMT 
,SUM(a.RECVAMT+a.RVSRECVAMT) in_tol, SUM(a.PAYAMT+a.RVSPAYAMT) out_tol,SUM((a.RECVAMT+a.RVSRECVAMT)+(a.PAYAMT+a.RVSPAYAMT)) dif_tol
FROM EACHUSER.RPONCLEARINGTAB a
LEFT JOIN BANK_GROUP b ON a.BGBK_ID = b.BGBK_ID
WHERE a.BIZDATE = '20150317' 
AND b.CTBK_ID IN( SELECT CTBK_ID FROM BANK_GROUP WHERE CTBK_ID !=  BGBK_ID  ) --全部 
-- b.CTBK_ID  = '0060000'
GROUP BY b.CTBK_ID  ,CLEARINGPHASE
ORDER BY CLEARINGPHASE ,  b.CTBK_ID
GO