WITH TEMP AS (
	SELECT '1' AS ACCTCODE, BIZDATE, CLEARINGPHASE, BRBK_ID, BGBK_ID, TXN_ID, SENDERID, BUSINESS_TYPE_ID, OP_TYPE, BRBK_NAME, BGBK_NAME, OPBK_ID, OPBK_NAME, TXN_NAME, COMPANY_ABBR_NAME, BUSINESS_TYPE_NAME,
	('0'||VARCHAR(CAST(YYYYMM AS INT) - 191100)) AS YYYYMM, CNT, AMT, 0 AS RVSCNT, 0 AS RVSAMT     
	FROM RPCLEARFEETAB
	WHERE COALESCE(CNT,0) <> 0
	AND YYYYMM = '201504' --AND OPBK_ID = '0040000' AND BGBK_ID = '0040000' AND BRBK_ID = '0040037'
	UNION ALL
	SELECT '0' AS ACCTCODE, BIZDATE, CLEARINGPHASE, BRBK_ID, BGBK_ID, TXN_ID, SENDERID, BUSINESS_TYPE_ID, OP_TYPE, BRBK_NAME, BGBK_NAME, OPBK_ID, OPBK_NAME, TXN_NAME, COMPANY_ABBR_NAME, BUSINESS_TYPE_NAME,
	('0'||VARCHAR(CAST(YYYYMM AS INT) - 191100)) AS YYYYMM, 0 AS CNT, 0 AS AMT, RVSCNT, RVSAMT
	FROM RPCLEARFEETAB
	WHERE COALESCE(RVSCNT,0) <> 0
	AND YYYYMM = '201504' --AND OPBK_ID = '0040000' AND BGBK_ID = '0040000' AND BRBK_ID = '0040037'
)

SELECT 
COALESCE(A.YYYYMM, B.YYYYMM) AS YYYYMM, 
COALESCE(A.BGBK_ID, B.BGBK_ID) AS BGBK_ID,
(SELECT VARCHAR(BGBK_NAME) FROM BANK_GROUP WHERE BGBK_ID = COALESCE(A.BGBK_ID, B.BGBK_ID)) AS BGBK_NAME, 
(CASE A.ACCTCODE WHEN '0' THEN '沖正' ELSE '一般' END) AS ACCTCODE
,COALESCE((SELECT SUM((CASE A.ACCTCODE WHEN '1' THEN COALESCE(CNT,0) ELSE COALESCE(RVSCNT,0) END)) FROM TEMP WHERE YYYYMM = A.YYYYMM AND BGBK_ID = A.BGBK_ID AND ACCTCODE = A.ACCTCODE AND OP_TYPE = 'S'),0) AS FIRECOUNT 
,COALESCE((SELECT SUM((CASE A.ACCTCODE WHEN '1' THEN COALESCE(AMT,0) ELSE COALESCE(RVSAMT,0) END)) FROM TEMP WHERE YYYYMM = A.YYYYMM AND BGBK_ID = A.BGBK_ID AND ACCTCODE = A.ACCTCODE AND OP_TYPE = 'S'),0) AS FIREAMT 
,COALESCE((SELECT SUM((CASE A.ACCTCODE WHEN '1' THEN COALESCE(CNT,0) ELSE COALESCE(RVSCNT,0) END)) FROM TEMP WHERE YYYYMM = A.YYYYMM AND BGBK_ID = A.BGBK_ID AND ACCTCODE = A.ACCTCODE AND OP_TYPE = 'O'),0) AS DEBITCOUNT 
,COALESCE((SELECT SUM((CASE A.ACCTCODE WHEN '1' THEN COALESCE(AMT,0) ELSE COALESCE(RVSAMT,0) END)) FROM TEMP WHERE YYYYMM = A.YYYYMM AND BGBK_ID = A.BGBK_ID AND ACCTCODE = A.ACCTCODE AND OP_TYPE = 'O'),0) AS DEBITAMT 
,COALESCE((SELECT SUM((CASE A.ACCTCODE WHEN '1' THEN COALESCE(CNT,0) ELSE COALESCE(RVSCNT,0) END)) FROM TEMP WHERE YYYYMM = A.YYYYMM AND BGBK_ID = A.BGBK_ID AND ACCTCODE = A.ACCTCODE AND OP_TYPE = 'I'),0) AS SAVECOUNT 
,COALESCE((SELECT SUM((CASE A.ACCTCODE WHEN '1' THEN COALESCE(AMT,0) ELSE COALESCE(RVSAMT,0) END)) FROM TEMP WHERE YYYYMM = A.YYYYMM AND BGBK_ID = A.BGBK_ID AND ACCTCODE = A.ACCTCODE AND OP_TYPE = 'I'),0) AS SAVEAMT
,COALESCE(B.FEE,0) AS ADJ_FEE
FROM (
	SELECT YYYYMM, BGBK_ID, ACCTCODE FROM TEMP GROUP BY YYYYMM, BGBK_ID, ACCTCODE
) AS A FULL JOIN (
    SELECT
    BFA.YYYYMM, BG.BGBK_ID, SUM(FEE) AS FEE
    FROM BRBK_FEE_ADJ AS BFA
    LEFT JOIN BANK_BRANCH AS BR ON BFA.BRBK_ID = BR.BRBK_ID
    LEFT JOIN BANK_GROUP AS BG ON BR.BGBK_ID = BG.BGBK_ID
    LEFT JOIN (
        SELECT DISTINCT BGBK_ID, OPBK_ID
        FROM BANK_OPBK
        WHERE COALESCE(START_DATE,'') <> '' 
    ) AS OP ON BG.OPBK_ID = OP.BGBK_ID AND BG.OPBK_ID = OP.OPBK_ID
    WHERE COALESCE(BFA.ACTIVE_DATE,'') <> ''
    AND BFA.YYYYMM = '010404' --AND BG.OPBK_ID = '0040000' AND BG.BGBK_ID = '0040000' AND BFA.BRBK_ID = '0040037'
    GROUP BY BFA.YYYYMM, BG.BGBK_ID
    HAVING SUM(FEE) <> 0
) AS B ON A.YYYYMM = B.YYYYMM AND A.BGBK_ID = B.BGBK_ID
ORDER BY ACCTCODE, BGBK_ID