--V3.0
WITH TEMP AS (
	SELECT BFA.YYYYMM, BG.OPBK_ID, COALESCE(BR.BGBK_ID,(CASE BFA.BRBK_ID WHEN '0188888' THEN '0188888' ELSE '' END)) AS BGBK_ID, SUM(BFA.FEE) AS FEE
	FROM BRBK_FEE_ADJ AS BFA LEFT JOIN BANK_BRANCH AS BR ON BFA.BRBK_ID = BR.BRBK_ID
	LEFT JOIN (
	    SELECT DISTINCT BGBK_ID, OPBK_ID, START_DATE, STOP_DATE
	    FROM BANK_OPBK
	    WHERE COALESCE(START_DATE,'') <> ''
	) AS BG ON BR.BGBK_ID = BG.BGBK_ID
	AND BFA.ACTIVE_DATE BETWEEN BG.START_DATE AND (CASE COALESCE(BG.STOP_DATE,'') WHEN '' THEN '99999999' ELSE BG.STOP_DATE END)
	WHERE COALESCE(BFA.ACTIVE_DATE,'') <> '' AND YYYYMM = '010404'
	GROUP BY BFA.YYYYMM, BG.OPBK_ID, BR.BGBK_ID
)

SELECT
COALESCE(B.YYYYMM, VARCHAR(INT(C.YYYYMM) + 191100)) AS YYYYMM,
COALESCE(B.BGBK_ID, C.BGBK_ID) AS BGBK_ID,
COALESCE(BGBK_NAME, (SELECT BGBK_NAME FROM BANK_GROUP WHERE BGBK_ID = C.BGBK_ID)) AS BGBK_NAME,
COALESCE(FIRECOUNT,0) AS FIRECOUNT, COALESCE(FIREAMT,0) AS FIREAMT,
COALESCE(DEBITCOUNT,0) AS DEBITCOUNT, COALESCE(DEBITAMT,0) AS DEBITAMT,
COALESCE(SAVECOUNT,0) AS SAVECOUNT, COALESCE(SAVEAMT,0) AS SAVEAMT,
COALESCE(B.ADJ_FEE, COALESCE(C.FEE, 0)) AS ADJ_FEE
FROM (
    SELECT
    A.YYYYMM, VARCHAR(A.BGBK_ID) AS BGBK_ID, (SELECT BGBK_NAME FROM BANK_GROUP WHERE BGBK_ID = A.BGBK_ID) AS BGBK_NAME
    ,(SELECT SUM(CNT+RVSCNT) FROM RPCLEARFEETAB WHERE YYYYMM = A.YYYYMM AND BGBK_ID = A.BGBK_ID AND OP_TYPE = 'S') AS FIRECOUNT
    ,(SELECT SUM(AMT+RVSAMT) FROM RPCLEARFEETAB WHERE YYYYMM = A.YYYYMM AND BGBK_ID = A.BGBK_ID AND OP_TYPE = 'S') AS FIREAMT
    ,(SELECT SUM(CNT+RVSCNT) FROM RPCLEARFEETAB WHERE YYYYMM = A.YYYYMM AND BGBK_ID = A.BGBK_ID AND OP_TYPE = 'O') AS DEBITCOUNT
    ,(SELECT SUM(AMT+RVSAMT) FROM RPCLEARFEETAB WHERE YYYYMM = A.YYYYMM AND BGBK_ID = A.BGBK_ID AND OP_TYPE = 'O') AS DEBITAMT
    ,(SELECT SUM(CNT+RVSCNT) FROM RPCLEARFEETAB WHERE YYYYMM = A.YYYYMM AND BGBK_ID = A.BGBK_ID AND OP_TYPE = 'I') AS SAVECOUNT
    ,(SELECT SUM(AMT+RVSAMT) FROM RPCLEARFEETAB WHERE YYYYMM = A.YYYYMM AND BGBK_ID = A.BGBK_ID AND OP_TYPE = 'I') AS SAVEAMT
    ,(SELECT FEE FROM TEMP WHERE VARCHAR(INT(YYYYMM) + 191100) = A.YYYYMM AND BGBK_ID = A.BGBK_ID) AS ADJ_FEE
    FROM RPCLEARFEETAB AS A
    WHERE A.YYYYMM = '201504'
    GROUP BY A.YYYYMM, A.BGBK_ID
    ORDER BY A.BGBK_ID
) B FULL OUTER JOIN TEMP AS C ON B.YYYYMM = VARCHAR(INT(C.YYYYMM) + 191100) AND B.BGBK_ID = C.BGBK_ID
ORDER BY BGBK_ID

--V2.0
WITH TEMP AS (
    SELECT D.YYYYMM, D.BGBK_ID, BG.OPBK_ID, D.FEE
    FROM (
        SELECT T.YYYYMM, T.BGBK_ID, SUM(T.FEE) AS FEE FROM (
            SELECT BFA.YYYYMM, BFA.BRBK_ID, FEE, 
            COALESCE(BR.BGBK_ID,(CASE BFA.BRBK_ID WHEN '0188888' THEN '0188888' ELSE '' END)) AS BGBK_ID
            FROM BRBK_FEE_ADJ AS BFA LEFT JOIN BANK_BRANCH AS BR ON BFA.BRBK_ID = BR.BRBK_ID
            WHERE COALESCE(BFA.ACTIVE_DATE,'') <> '' AND YYYYMM = '010404'
        ) AS T GROUP BY T.YYYYMM, T.BGBK_ID
    ) AS D LEFT JOIN BANK_GROUP AS BG ON D.BGBK_ID = BG.BGBK_ID
)

SELECT
COALESCE(B.YYYYMM, VARCHAR(INT(C.YYYYMM) + 191100)) AS YYYYMM,
COALESCE(B.BGBK_ID, C.BGBK_ID) AS BGBK_ID,
COALESCE(BGBK_NAME, (SELECT BGBK_NAME FROM BANK_GROUP WHERE BGBK_ID = C.BGBK_ID)) AS BGBK_NAME,
COALESCE(FIRECOUNT,0) AS FIRECOUNT, COALESCE(FIREAMT,0) AS FIREAMT,
COALESCE(DEBITCOUNT,0) AS DEBITCOUNT, COALESCE(DEBITAMT,0) AS DEBITAMT,
COALESCE(SAVECOUNT,0) AS SAVECOUNT, COALESCE(SAVEAMT,0) AS SAVEAMT,
COALESCE(B.ADJ_FEE, COALESCE(C.FEE, 0)) AS ADJ_FEE
FROM (
    SELECT
    A.YYYYMM, VARCHAR(A.BGBK_ID) AS BGBK_ID, (SELECT BGBK_NAME FROM BANK_GROUP WHERE BGBK_ID = A.BGBK_ID) AS BGBK_NAME
    ,(SELECT SUM(CNT+RVSCNT) FROM RPCLEARFEETAB WHERE YYYYMM = A.YYYYMM AND BGBK_ID = A.BGBK_ID AND OP_TYPE = 'S') AS FIRECOUNT
    ,(SELECT SUM(AMT+RVSAMT) FROM RPCLEARFEETAB WHERE YYYYMM = A.YYYYMM AND BGBK_ID = A.BGBK_ID AND OP_TYPE = 'S') AS FIREAMT
    ,(SELECT SUM(CNT+RVSCNT) FROM RPCLEARFEETAB WHERE YYYYMM = A.YYYYMM AND BGBK_ID = A.BGBK_ID AND OP_TYPE = 'O') AS DEBITCOUNT
    ,(SELECT SUM(AMT+RVSAMT) FROM RPCLEARFEETAB WHERE YYYYMM = A.YYYYMM AND BGBK_ID = A.BGBK_ID AND OP_TYPE = 'O') AS DEBITAMT
    ,(SELECT SUM(CNT+RVSCNT) FROM RPCLEARFEETAB WHERE YYYYMM = A.YYYYMM AND BGBK_ID = A.BGBK_ID AND OP_TYPE = 'I') AS SAVECOUNT
    ,(SELECT SUM(AMT+RVSAMT) FROM RPCLEARFEETAB WHERE YYYYMM = A.YYYYMM AND BGBK_ID = A.BGBK_ID AND OP_TYPE = 'I') AS SAVEAMT
    ,(SELECT FEE FROM TEMP WHERE VARCHAR(INT(YYYYMM) + 191100) = A.YYYYMM AND BGBK_ID = A.BGBK_ID) AS ADJ_FEE
    FROM RPCLEARFEETAB AS A
    WHERE A.YYYYMM = '201504'
    GROUP BY A.YYYYMM, A.BGBK_ID
    ORDER BY A.BGBK_ID
) B FULL OUTER JOIN TEMP AS C ON B.YYYYMM = VARCHAR(INT(C.YYYYMM) + 191100) AND B.BGBK_ID = C.BGBK_ID
ORDER BY BGBK_ID

--V1.0
WITH TEMP AS (
    SELECT D.YYYYMM, D.BGBK_ID, BG.OPBK_ID, D.FEE
    FROM (
        SELECT T.YYYYMM, T.BGBK_ID, SUM(T.FEE) AS FEE FROM (
            SELECT BFA.YYYYMM, BFA.BRBK_ID, FEE, 
            COALESCE(BR.BGBK_ID,(CASE BFA.BRBK_ID WHEN '0188888' THEN '0188888' ELSE '' END)) AS BGBK_ID
            FROM BRBK_FEE_ADJ AS BFA LEFT JOIN BANK_BRANCH AS BR ON BFA.BRBK_ID = BR.BRBK_ID
            WHERE COALESCE(BFA.ACTIVE_DATE,'') <> ''
            AND BFA.YYYYMM = '010404'
        ) AS T GROUP BY T.YYYYMM, T.BGBK_ID
    ) AS D LEFT JOIN BANK_GROUP AS BG ON D.BGBK_ID = BG.BGBK_ID
)

SELECT
A.YYYYMM, VARCHAR(A.BGBK_ID) AS BGBK_ID, (SELECT BGBK_NAME FROM BANK_GROUP WHERE BGBK_ID = A.BGBK_ID) AS BGBK_NAME
,COALESCE((SELECT SUM(CNT+RVSCNT) FROM RPCLEARFEETAB WHERE YYYYMM = A.YYYYMM AND BGBK_ID = A.BGBK_ID AND OP_TYPE = 'S'),0) AS FIRECOUNT
,COALESCE((SELECT SUM(AMT+RVSAMT) FROM RPCLEARFEETAB WHERE YYYYMM = A.YYYYMM AND BGBK_ID = A.BGBK_ID AND OP_TYPE = 'S'),0) AS FIREAMT
,COALESCE((SELECT SUM(CNT+RVSCNT) FROM RPCLEARFEETAB WHERE YYYYMM = A.YYYYMM AND BGBK_ID = A.BGBK_ID AND OP_TYPE = 'O'),0) AS DEBITCOUNT
,COALESCE((SELECT SUM(AMT+RVSAMT) FROM RPCLEARFEETAB WHERE YYYYMM = A.YYYYMM AND BGBK_ID = A.BGBK_ID AND OP_TYPE = 'O'),0) AS DEBITAMT
,COALESCE((SELECT SUM(CNT+RVSCNT) FROM RPCLEARFEETAB WHERE YYYYMM = A.YYYYMM AND BGBK_ID = A.BGBK_ID AND OP_TYPE = 'I'),0) AS SAVECOUNT
,COALESCE((SELECT SUM(AMT+RVSAMT) FROM RPCLEARFEETAB WHERE YYYYMM = A.YYYYMM AND BGBK_ID = A.BGBK_ID AND OP_TYPE = 'I'),0) AS SAVEAMT
,COALESCE((SELECT FEE FROM TEMP WHERE VARCHAR(INT(YYYYMM) + 191100) = A.YYYYMM AND BGBK_ID = A.BGBK_ID),0) AS ADJ_FEE
FROM RPCLEARFEETAB AS A
WHERE A.YYYYMM = '201504'
GROUP BY A.YYYYMM, A.BGBK_ID
ORDER BY A.BGBK_ID