--V3.0
WITH TEMP AS (
    SELECT BIZDATE, CLEARINGPHASE, BGBK_ID ,'一般' AS ACCTCODE, OP_TYPE, CNT, AMT, RVSCNT, RVSAMT
    FROM EACHUSER.RPCLEARFEETAB AS X
    WHERE  BIZDATE >= '20150304'  AND  BIZDATE <= '20150304'
    UNION ALL
    SELECT BIZDATE, CLEARINGPHASE, BGBK_ID ,'沖正' AS ACCTCODE, OP_TYPE, CNT, AMT, RVSCNT, RVSAMT
    FROM EACHUSER.RPCLEARFEETAB AS Y
    WHERE COALESCE(RVSCNT,0) <> 0
    AND  BIZDATE >= '20150304'  AND  BIZDATE <= '20150304' 
) 
SELECT 
BIZDATE, VARCHAR(A.BGBK_ID) AS BGBK_ID, 
BGBK_ID || '-' || (SELECT BGBK_NAME FROM BANK_GROUP BG WHERE A.BGBK_ID = BG.BGBK_ID) AS BANKID, 
VARCHAR(CLEARINGPHASE) AS CLEARINGPHASE, ACCTCODE, 
COALESCE((SELECT SUM(CASE ACCTCODE WHEN '一般' THEN COALESCE(CNT,0) ELSE COALESCE(RVSCNT,0) END) FROM TEMP WHERE BIZDATE = A.BIZDATE AND BGBK_ID = A.BGBK_ID AND CLEARINGPHASE = A.CLEARINGPHASE AND ACCTCODE = A.ACCTCODE AND OP_TYPE = 'S'),0) AS FIRECOUNT, 
COALESCE((SELECT SUM(CASE ACCTCODE WHEN '一般' THEN COALESCE(AMT,0) ELSE COALESCE(RVSAMT,0) END) FROM TEMP WHERE BIZDATE = A.BIZDATE AND BGBK_ID = A.BGBK_ID AND CLEARINGPHASE = A.CLEARINGPHASE AND ACCTCODE = A.ACCTCODE AND OP_TYPE = 'S'),0) AS FIREAMT, 
COALESCE((SELECT SUM(CASE ACCTCODE WHEN '一般' THEN COALESCE(CNT,0) ELSE COALESCE(RVSCNT,0) END) FROM TEMP WHERE BIZDATE = A.BIZDATE AND BGBK_ID = A.BGBK_ID AND CLEARINGPHASE = A.CLEARINGPHASE AND ACCTCODE = A.ACCTCODE AND OP_TYPE = 'O'),0) AS DEBITCOUNT, 
COALESCE((SELECT SUM(CASE ACCTCODE WHEN '一般' THEN COALESCE(AMT,0) ELSE COALESCE(RVSAMT,0) END) FROM TEMP WHERE BIZDATE = A.BIZDATE AND BGBK_ID = A.BGBK_ID AND CLEARINGPHASE = A.CLEARINGPHASE AND ACCTCODE = A.ACCTCODE AND OP_TYPE = 'O'),0) AS DEBITAMT, 
COALESCE((SELECT SUM(CASE ACCTCODE WHEN '一般' THEN COALESCE(CNT,0) ELSE COALESCE(RVSCNT,0) END) FROM TEMP WHERE BIZDATE = A.BIZDATE AND BGBK_ID = A.BGBK_ID AND CLEARINGPHASE = A.CLEARINGPHASE AND ACCTCODE = A.ACCTCODE AND OP_TYPE = 'I'),0) AS SAVECOUNT, 
COALESCE((SELECT SUM(CASE ACCTCODE WHEN '一般' THEN COALESCE(AMT,0) ELSE COALESCE(RVSAMT,0) END) FROM TEMP WHERE BIZDATE = A.BIZDATE AND BGBK_ID = A.BGBK_ID AND CLEARINGPHASE = A.CLEARINGPHASE AND ACCTCODE = A.ACCTCODE AND OP_TYPE = 'I'),0) AS SAVEAMT 
FROM (
    SELECT BIZDATE, BGBK_ID, CLEARINGPHASE, ACCTCODE
    FROM TEMP
    GROUP BY BIZDATE, BGBK_ID, CLEARINGPHASE, ACCTCODE 
) AS A 
ORDER BY A.BGBK_ID, A.ACCTCODE, A.BIZDATE, A.CLEARINGPHASE 

--V2.0
WITH TEMP AS (
    SELECT BIZDATE, CLEARINGPHASE, BGBK_ID ,'一般' AS ACCTCODE, OP_TYPE, CNT, AMT, RVSCNT, RVSAMT
    FROM EACHUSER.RPCLEARFEETAB X
    --WHERE BIZDATE >= '20150225' AND BIZDATE <= '20150225'
    --AND CLEARINGPHASE = '01' AND BGBK_ID = '0040000'
    --AND (SELECT OPBK_ID FROM BANK_GROUP WHERE BGBK_ID = X.BGBK_ID) = '0040000'
    UNION ALL
    SELECT BIZDATE, CLEARINGPHASE, BGBK_ID ,'調整' AS ACCTCODE, OP_TYPE, CNT, AMT, RVSCNT, RVSAMT
    FROM EACHUSER.RPCLEARFEETAB Y
    WHERE COALESCE(RVSCNT,0) <> 0
    --AND BIZDATE >= '20150225' AND BIZDATE <= '20150225'
    --AND CLEARINGPHASE = '01' AND BGBK_ID = '0040000'
    --AND (SELECT OPBK_ID FROM BANK_GROUP WHERE BGBK_ID = Y.BGBK_ID) = '0040000'
)

SELECT
BIZDATE, VARCHAR(A.BGBK_ID) AS BGBK_ID, BGBK_ID || '-' || (SELECT BGBK_NAME FROM BANK_GROUP BG WHERE A.BGBK_ID = BG.BGBK_ID) AS BANKID,
VARCHAR(CLEARINGPHASE) AS CLEARINGPHASE, ACCTCODE,
(SELECT COUNT(*) FROM TEMP WHERE BIZDATE = A.BIZDATE AND BGBK_ID = A.BGBK_ID AND CLEARINGPHASE = A.CLEARINGPHASE AND ACCTCODE = A.ACCTCODE AND OP_TYPE = 'S') AS FIRECOUNT,
COALESCE((SELECT SUM(CASE ACCTCODE WHEN '一般' THEN COALESCE(AMT,0) ELSE COALESCE(RVSAMT,0) END) FROM TEMP WHERE BIZDATE = A.BIZDATE AND BGBK_ID = A.BGBK_ID AND CLEARINGPHASE = A.CLEARINGPHASE AND ACCTCODE = A.ACCTCODE AND OP_TYPE = 'S'),0) AS FIREAMT,
(SELECT COUNT(*) FROM TEMP WHERE BIZDATE = A.BIZDATE AND BGBK_ID = A.BGBK_ID AND CLEARINGPHASE = A.CLEARINGPHASE AND ACCTCODE = A.ACCTCODE AND OP_TYPE = 'O') AS DEBITCOUNT,
COALESCE((SELECT SUM(CASE ACCTCODE WHEN '一般' THEN COALESCE(AMT,0) ELSE COALESCE(RVSAMT,0) END) FROM TEMP WHERE BIZDATE = A.BIZDATE AND BGBK_ID = A.BGBK_ID AND CLEARINGPHASE = A.CLEARINGPHASE AND ACCTCODE = A.ACCTCODE AND OP_TYPE = 'O'),0) AS DEBITAMT,
(SELECT COUNT(*) FROM TEMP WHERE BIZDATE = A.BIZDATE AND BGBK_ID = A.BGBK_ID AND CLEARINGPHASE = A.CLEARINGPHASE AND ACCTCODE = A.ACCTCODE AND OP_TYPE = 'I') AS SAVECOUNT,
COALESCE((SELECT SUM(CASE ACCTCODE WHEN '一般' THEN COALESCE(AMT,0) ELSE COALESCE(RVSAMT,0) END) FROM TEMP WHERE BIZDATE = A.BIZDATE AND BGBK_ID = A.BGBK_ID AND CLEARINGPHASE = A.CLEARINGPHASE AND ACCTCODE = A.ACCTCODE AND OP_TYPE = 'I'),0) AS SAVEAMT
FROM (
    SELECT BIZDATE, BGBK_ID, CLEARINGPHASE, ACCTCODE
    FROM TEMP 
    GROUP BY BIZDATE, BGBK_ID, CLEARINGPHASE, ACCTCODE
) AS A
ORDER BY A.BGBK_ID, A.ACCTCODE, A.BIZDATE, A.CLEARINGPHASE
GO

--V1.0
WITH TEMP AS (     
    SELECT SENDERHEAD, OUTHEAD, INHEAD, SENDERBANKID, OUTBANKID, INBANKID,     
    (CASE ACCTCODE WHEN '0' THEN '0' ELSE '1' END) AS ACCTCODE,     
    CLEARINGPHASE, SENDERFEE, INFEE, OUTFEE, TXAMT, NEWRESULT, RC1, RC2, RC3, TXDT     
    FROM RPONBLOCKTAB A 	
    WHERE  ((NEWRESULT = 'R' AND ACCTCODE = '0') OR NEWRESULT <> 'R')
    AND BIZDATE >= '20150225'  AND  BIZDATE <= '20150225'  --AND  CLEARINGPHASE = '01'  
    AND  (SENDERACQUIRE = '0040000' OR OUTACQUIRE = '0040000' OR INACQUIRE = '0040000')  
    AND  (SENDERHEAD = '0040000' OR OUTHEAD = '0040000' OR INHEAD = '0040000') 
)
SELECT 
COALESCE((A.BANKID || '-' || B.BGBK_NAME),'') AS BANKID, 
B.BGBK_ID, COALESCE(B.BGBK_NAME,'') AS BGBK_NAME, A.CLEARINGPHASE,
(CASE ACCTCODE WHEN '0' THEN '調整' ELSE '一般' END) AS ACCTCODE, 
(SELECT COUNT(*) FROM TEMP WHERE SENDERHEAD = A.BANKID AND CLEARINGPHASE = A.CLEARINGPHASE AND ACCTCODE = A.ACCTCODE) AS FIRECOUNT, 
COALESCE((SELECT SUM(SENDERFEE) FROM TEMP WHERE SENDERHEAD = A.BANKID AND CLEARINGPHASE = A.CLEARINGPHASE AND ACCTCODE = A.ACCTCODE),0) AS FIREAMT, 
(SELECT COUNT(*) FROM TEMP WHERE OUTHEAD = A.BANKID AND CLEARINGPHASE = A.CLEARINGPHASE AND ACCTCODE = A.ACCTCODE) AS DEBITCOUNT, 
COALESCE((SELECT SUM(OUTFEE) FROM TEMP WHERE OUTHEAD = A.BANKID AND CLEARINGPHASE = A.CLEARINGPHASE AND ACCTCODE = A.ACCTCODE),0) AS DEBITAMT, 
(SELECT COUNT(*) FROM TEMP WHERE INHEAD = A.BANKID AND CLEARINGPHASE = A.CLEARINGPHASE AND ACCTCODE = A.ACCTCODE) AS SAVECOUNT, 
COALESCE((SELECT SUM(INFEE) FROM TEMP WHERE INHEAD = A.BANKID AND CLEARINGPHASE = A.CLEARINGPHASE AND ACCTCODE = A.ACCTCODE),0) AS SAVEAMT 
FROM (
     SELECT SENDERHEAD AS BANKID, CLEARINGPHASE, ACCTCODE FROM TEMP GROUP BY SENDERHEAD, CLEARINGPHASE, ACCTCODE
     UNION     SELECT OUTHEAD, CLEARINGPHASE, ACCTCODE FROM TEMP GROUP BY OUTHEAD, CLEARINGPHASE, ACCTCODE
     UNION     SELECT INHEAD, CLEARINGPHASE, ACCTCODE FROM TEMP GROUP BY INHEAD, CLEARINGPHASE, ACCTCODE 
) AS A LEFT JOIN (
     SELECT BG.BGBK_ID, BG.BGBK_NAME, BG.OPBK_ID, OP.BGBK_NAME AS OPBK_NAME
     FROM BANK_GROUP BG LEFT JOIN BANK_GROUP OP ON BG.OPBK_ID = OP.BGBK_ID 
) AS B ON A.BANKID = B.BGBK_ID 
ORDER BY BANKID, CLEARINGPHASE, ACCTCODE 