--V1.0
SELECT VARCHAR(SUBSTR(TRANS_DATE(BIZDATE,'T','/'),2,9)) AS BIZDATE
,COALESCE((SELECT SUM(COALESCE(CNT,0))+SUM(COALESCE(RVSCNT,0)) FROM RPCLEARFEETAB WHERE BIZDATE = A.BIZDATE AND OPBK_ID = A.OPBK_ID AND BGBK_ID = A.BGBK_ID AND BRBK_ID = A.BRBK_ID AND OP_TYPE = 'S'),0) AS FIRECOUNT
,COALESCE((SELECT SUM(COALESCE(AMT,0))+SUM(COALESCE(RVSAMT,0)) FROM RPCLEARFEETAB WHERE BIZDATE = A.BIZDATE AND OPBK_ID = A.OPBK_ID AND BGBK_ID = A.BGBK_ID AND BRBK_ID = A.BRBK_ID AND OP_TYPE = 'S'),0) AS FIREAMT
,COALESCE((SELECT SUM(COALESCE(CNT,0))+SUM(COALESCE(RVSCNT,0)) FROM RPCLEARFEETAB WHERE BIZDATE = A.BIZDATE AND OPBK_ID = A.OPBK_ID AND BGBK_ID = A.BGBK_ID AND BRBK_ID = A.BRBK_ID AND OP_TYPE = 'O'),0) AS DEBITCOUNT
,COALESCE((SELECT SUM(COALESCE(AMT,0))+SUM(COALESCE(RVSAMT,0)) FROM RPCLEARFEETAB WHERE BIZDATE = A.BIZDATE AND OPBK_ID = A.OPBK_ID AND BGBK_ID = A.BGBK_ID AND BRBK_ID = A.BRBK_ID AND OP_TYPE = 'O'),0) AS DEBITAMT
,COALESCE((SELECT SUM(COALESCE(CNT,0))+SUM(COALESCE(RVSCNT,0)) FROM RPCLEARFEETAB WHERE BIZDATE = A.BIZDATE AND OPBK_ID = A.OPBK_ID AND BGBK_ID = A.BGBK_ID AND BRBK_ID = A.BRBK_ID AND OP_TYPE = 'I'),0) AS SAVECOUNT
,COALESCE((SELECT SUM(COALESCE(AMT,0))+SUM(COALESCE(RVSAMT,0)) FROM RPCLEARFEETAB WHERE BIZDATE = A.BIZDATE AND OPBK_ID = A.OPBK_ID AND BGBK_ID = A.BGBK_ID AND BRBK_ID = A.BRBK_ID AND OP_TYPE = 'I'),0) AS SAVEAMT
FROM RPCLEARFEETAB A
WHERE YYYYMM = '201503' AND A.OPBK_ID = '9970018' AND BGBK_ID = '1610000' AND BRBK_ID = '1610000'
GROUP BY BIZDATE, OPBK_ID, BGBK_ID, BRBK_ID
ORDER BY BIZDATE