WITH TEMP AS (
     SELECT
     DOUBLE(DATE_DIFF(ENDTIME, DT_REQ_1)) / CAST (1000000 AS BIGINT) AS TIME_1,
     DOUBLE(DATE_DIFF(DT_RSP_1, DT_REQ_2)) / CAST (1000000 AS BIGINT) AS TIME_2,
     (DOUBLE(DATE_DIFF(DT_REQ_2, DT_REQ_1)) + DOUBLE(DATE_DIFF(DT_RSP_2, DT_RSP_1))) / CAST (1000000 AS BIGINT) AS TIME_3,
     C.*
     FROM (
         SELECT
         (CASE WHEN RC2 = '3001' THEN 1 ELSE 0 END) OKCOUNT,
         (CASE WHEN RC2 NOT IN ('3001','0601') THEN 1 ELSE 0 END) FAILCOUNT,
         (CASE WHEN RC2 = '0601' THEN 1 ELSE 0 END) PENDCOUNT,
         INTEGER(SUBSTR(A.TXDT,9,2)) AS HOURLAP, A.RESULTSTATUS,
         A.PCODE, SUBSTR(COALESCE(A.PCODE,'0000'),4,1) AS TXN_TYPE, A.RC2, A.SENDERSTATUS,
         COALESCE(A.DT_RSP_2, COALESCE(A.DT_RSP_1, COALESCE(A.DT_REQ_2, COALESCE(A.DT_REQ_1, 0)))) AS ENDTIME,
         (CASE WHEN LENGTH(COALESCE(A.DT_REQ_1,''))=0 THEN '0' ELSE A.DT_REQ_1 END ) DT_REQ_1,
         (CASE WHEN LENGTH(COALESCE(A.DT_REQ_2,''))=0 THEN '0' ELSE A.DT_REQ_2 END ) DT_REQ_2,
         (CASE WHEN LENGTH(COALESCE(A.DT_REQ_3,''))=0 THEN '0' ELSE A.DT_REQ_3 END ) DT_REQ_3,
         (CASE WHEN LENGTH(COALESCE(A.DT_RSP_1,''))=0 THEN '0' ELSE A.DT_RSP_1 END ) DT_RSP_1,
         (CASE WHEN LENGTH(COALESCE(A.DT_RSP_2,''))=0 THEN '0' ELSE A.DT_RSP_2 END ) DT_RSP_2,
         (CASE WHEN LENGTH(COALESCE(A.DT_RSP_3,''))=0 THEN '0' ELSE A.DT_RSP_3 END ) DT_RSP_3,
         A.CLEARINGPHASE, A.SENDERACQUIRE, A.OUTACQUIRE, A.INACQUIRE, A.SENDERHEAD, A.OUTHEAD, A.INHEAD
         FROM ONBLOCKTAB AS A
         WHERE ( A.RESULTSTATUS IN ('A', 'R') OR (A.RESULTSTATUS = 'P' AND A.SENDERSTATUS <> '1') ) AND COALESCE(DT_REQ_2,'') <> ''
         AND A.BIZDATE = '20150622'  
         --AND A.PCODE = ?  AND (A.SENDERACQUIRE = ? OR A.OUTACQUIRE = ? OR A.INACQUIRE = ?)  AND (A.SENDERHEAD = ? OR A.OUTHEAD = ? OR A.INHEAD = ?)  AND A.CLEARINGPHASE = ?
      ) AS C 
), TEMP_ AS (
    SELECT HOURLAP,
    SUM(OKCOUNT + FAILCOUNT + PENDCOUNT) AS TOTALCOUNT, SUM(OKCOUNT) AS OKCOUNT,
    SUM(FAILCOUNT) AS FAILCOUNT, SUM(PENDCOUNT) AS PENDCOUNT
    FROM TEMP
    GROUP BY HOURLAP
)

SELECT A.*,
COALESCE((SELECT SUM(CASE WHEN (OKCOUNT + FAILCOUNT) > 0 THEN 1 ELSE 0 END) FROM TEMP_), 0) AS PERIOD_COUNT,
COALESCE(B.TOTALCOUNT,0) AS TOTALCOUNT, COALESCE(B.OKCOUNT,0) AS OKCOUNT,
COALESCE(B.FAILCOUNT,0) AS FAILCOUNT, COALESCE(B.PENDCOUNT,0) AS PENDCOUNT,
DECIMAL(COALESCE((SELECT SUM(TIME_1) / CAST(COUNT(*) AS BIGINT) FROM TEMP WHERE HOURLAP = A.HOURLAP AND RC2 <> '0601'),0),18,2) PRCTIME,
DECIMAL(COALESCE((SELECT SUM(TIME_2) / CAST(COUNT(*) AS BIGINT) FROM TEMP WHERE HOURLAP = A.HOURLAP AND TXN_TYPE = '2' AND RC2 <> '0601'),0),18,2) +
DECIMAL(COALESCE((SELECT SUM((DOUBLE(DATE_DIFF(DT_RSP_3, DT_REQ_3)) / CAST (1000000 AS BIGINT))) / CAST(COUNT(*) AS BIGINT) FROM TEMP WHERE HOURLAP = A.HOURLAP AND TXN_TYPE = '4' AND DT_REQ_3 <> 0 AND RC2 <> '0601'),0),18,2) SAVETIME,
DECIMAL(COALESCE((SELECT SUM(TIME_2) / CAST(COUNT(*) AS BIGINT) FROM TEMP WHERE HOURLAP = A.HOURLAP AND TXN_TYPE IN ('1','3','4') AND RC2 <> '0601'),0),18,2) DEBITTIME,
DECIMAL(COALESCE((SELECT SUM(CASE TXN_TYPE WHEN '4' THEN (DATE_DIFF(DT_REQ_2,DT_REQ_1) + DATE_DIFF(DT_REQ_3,DT_RSP_1) + DATE_DIFF(DT_RSP_2,DT_RSP_3)) / CAST (1000000 AS BIGINT) ELSE TIME_3 END) / CAST(COUNT(*) AS BIGINT) FROM TEMP WHERE HOURLAP = A.HOURLAP AND RC2 <> '0601'),0),18,2) ACHPRCTIME
FROM HOURITEM AS A LEFT JOIN TEMP_ AS B ON A.HOURLAP = B.HOURLAP
WHERE A.HOURLAP IS NOT NULL
ORDER BY A.HOURLAP