--V2.0
SELECT
VARCHAR(A.BIZDATE) AS BIZDATE, VARCHAR(A.CLEARINGPHASE) AS CLEARINGPHASE, VARCHAR(A.BGBK_ID) AS BGBK_ID, 
COALESCE((SELECT BGBK_NAME FROM BANK_GROUP WHERE BGBK_ID = A.BGBK_ID),'') AS BGBK_NAME,
SUM(A.RECVCNT) AS RECVCNT, SUM(A.RECVAMT) AS RECVAMT, SUM(A.PAYCNT) AS PAYCNT, SUM(A.PAYAMT) AS PAYAMT,
SUM(A.RVSRECVCNT) AS RVSRECVCNT, SUM(A.RVSRECVAMT) ASRVSRECVAMT, SUM(A.RVSPAYCNT) AS RVSPAYCNT, SUM(A.RVSPAYAMT) AS RVSPAYAMT,
SUM(A.RECVAMT + A.RVSRECVAMT) IN_TOL, SUM(A.PAYAMT + A.RVSPAYAMT) OUT_TOL, SUM((A.RECVAMT + A.RVSRECVAMT) + (A.PAYAMT + A.RVSPAYAMT)) DIF_TOL
FROM RPONCLEARINGTAB AS A
WHERE A.BIZDATE = '20150511'
AND CLEARINGPHASE = '01'
AND OPBK_ID = '4530000'
AND BGBK_ID = '4530000'
GROUP BY A.BIZDATE, A.CLEARINGPHASE, A.BGBK_ID
ORDER BY A.BIZDATE, A.CLEARINGPHASE, A.BGBK_ID

--總行GROUP
SELECT
 VARCHAR(a.BGBK_ID) BGBK_ID
, (select coalesce(bgbk_name,'') from bank_group where bgbk_id=a.BGBK_ID) BGBK_NAME
,VARCHAR(a.CLEARINGPHASE) CLEARINGPHASE 
,SUM(a.RECVCNT) RECVCNT , SUM(a.RECVAMT) RECVAMT ,SUM(a.PAYCNT) PAYCNT , SUM(a.PAYAMT ) PAYAMT ,SUM(a.RVSRECVCNT) RVSRECVCNT , SUM(a.RVSRECVAMT) RVSRECVAMT ,SUM(a.RVSPAYCNT) RVSPAYCNT ,SUM(a.RVSPAYAMT) RVSPAYAMT 
,SUM(a.RECVAMT+a.RVSRECVAMT) in_tol, SUM(a.PAYAMT+a.RVSPAYAMT) out_tol,SUM((a.RECVAMT+a.RVSRECVAMT)+(a.PAYAMT+a.RVSPAYAMT)) dif_tol   
FROM  RPONCLEARINGTAB a
LEFT JOIN EACH_TXN_CODE T ON a.PCODE = T.EACH_TXN_ID
LEFT JOIN BUSINESS_TYPE B ON T.BUSINESS_TYPE_ID=B.BUSINESS_TYPE_ID
--WHERE a.BIZDATE = ?   
GROUP BY a.CLEARINGPHASE  ,a.BGBK_ID , 
ORDER BY   a.BGBK_ID   ,  a.CLEARINGPHASE 
 --, b.BUSINESS_TYPE_ID 
 


--分行GROUP
SELECT
 VARCHAR(a.BGBK_ID) BGBK_ID
, (select coalesce(bgbk_name,'') from bank_group where bgbk_id=a.BGBK_ID) BGBK_NAME
,a.BRBK_ID 
, (select coalesce(brbk_name,'') from bank_branch where brbk_id=a.BRBK_ID) BRBK_NAME
,VARCHAR(a.CLEARINGPHASE) CLEARINGPHASE 
--,a.PCODE ,b.BUSINESS_TYPE_ID ||'\n'|| b.BUSINESS_TYPE_NAME BUSINESS_TYPE_ID
,SUM(a.RECVCNT) RECVCNT , SUM(a.RECVAMT) RECVAMT ,SUM(a.PAYCNT) PAYCNT , SUM(a.PAYAMT ) PAYAMT ,SUM(a.RVSRECVCNT) RVSRECVCNT , SUM(a.RVSRECVAMT) RVSRECVAMT ,SUM(a.RVSPAYCNT) RVSPAYCNT ,SUM(a.RVSPAYAMT) RVSPAYAMT 
--,SUM(a.RECVAMT+a.RVSRECVAMT) in_tol, SUM(a.PAYAMT+a.RVSPAYAMT) out_tol,SUM((a.RECVAMT+a.RVSRECVAMT)-(a.PAYAMT+a.RVSPAYAMT)) dif_tol   
,SUM(a.RECVAMT+a.RVSRECVAMT) in_tol, SUM(a.PAYAMT+a.RVSPAYAMT) out_tol,SUM((a.RECVAMT+a.RVSRECVAMT)+(a.PAYAMT+a.RVSPAYAMT)) dif_tol   
FROM  RPONCLEARINGTAB a
LEFT JOIN EACH_TXN_CODE T ON a.PCODE = T.EACH_TXN_ID
LEFT JOIN BUSINESS_TYPE B ON T.BUSINESS_TYPE_ID=B.BUSINESS_TYPE_ID
--WHERE a.BIZDATE = ?   
GROUP BY a.CLEARINGPHASE  ,a.BGBK_ID , a.BRBK_ID
ORDER BY   a.BGBK_ID ,a.BRBK_ID  ,  a.CLEARINGPHASE 
 --, b.BUSINESS_TYPE_ID 



--分行未GROUP
SELECT a.BGBK_ID , coalesce((select bgbk_name from bank_group where bgbk_id=a.BGBK_ID),'') BGBK_NAME
,a.BRBK_ID , coalesce((select brbk_name from bank_branch where brbk_id=a.BRBK_ID),'') BRBK_NAME
,a.CLEARINGPHASE || '' CLEARINGPHASE 
,a.PCODE ,b.BUSINESS_TYPE_ID , b.BUSINESS_TYPE_NAME 
,a.RECVCNT , a.RECVAMT 
,a.PAYCNT  , a.PAYAMT  
,a.RVSRECVCNT , a.RVSRECVAMT 
,a.RVSPAYCNT ,a.RVSPAYAMT 
, a.RECVAMT+a.RVSRECVAMT in_tol, a.PAYAMT+a.RVSPAYAMT out_tol
,(a.RECVAMT+a.RVSRECVAMT)-(a.PAYAMT+a.RVSPAYAMT) dif_tol   
FROM  RPONCLEARINGTAB a
LEFT JOIN EACH_TXN_CODE T ON a.PCODE = T.EACH_TXN_ID
LEFT JOIN BUSINESS_TYPE B ON T.BUSINESS_TYPE_ID=B.BUSINESS_TYPE_ID
--WHERE a.BIZDATE = ?   
ORDER BY a.CLEARINGPHASE  ,a.BGBK_ID , a.BRBK_ID , b.BUSINESS_TYPE_ID



--20150227前的舊語法
SELECT a.BANKID || '
' || (select coalesce(bgbk_name,'') from bank_group where bgbk_id=a.BANKID) BANKID 
,COUNT( a.RECVCNT ) RECVCNT ,SUM( a.RECVAMT ) RECVAMT
,COUNT( a.PAYCNT ) PAYCNT ,SUM( a.PAYAMT ) PAYAMT  
,COUNT( a.RVSRECVCNT ) RVSRECVCNT,SUM( a.RVSRECVAMT ) RVSRECVAMT
,COUNT( a.RVSPAYCNT ) RVSPAYCNT,SUM( a.RVSPAYAMT ) RVSPAYAMT  
,SUM( a.RECVAMT+a.RVSRECVAMT) in_tol,SUM( a.PAYAMT+a.RVSPAYAMT) out_tol
,SUM((a.RECVAMT+a.RVSRECVAMT)-(a.PAYAMT+a.RVSPAYAMT)) dif_tol   
,a.CLEARINGPHASE || '' CLEARINGPHASE 
FROM  ONCLEARINGTAB a WHERE a.BIZDATE = ?   
GROUP BY a.BANKID ,a.CLEARINGPHASE  
ORDER BY BANKID 