--總行GROUP 業務類別版
SELECT
 VARCHAR(a.BGBK_ID) BGBK_ID
, (select coalesce(bgbk_name,'') from bank_group where bgbk_id=a.BGBK_ID) BGBK_NAME
,VARCHAR(a.CLEARINGPHASE) CLEARINGPHASE ,T.EACH_TXN_ID , T.EACH_TXN_NAME --交易類別版本
,SUM(a.RECVCNT) RECVCNT , SUM(a.RECVAMT) RECVAMT ,SUM(a.PAYCNT) PAYCNT , SUM(a.PAYAMT ) PAYAMT ,SUM(a.RVSRECVCNT) RVSRECVCNT , SUM(a.RVSRECVAMT) RVSRECVAMT ,SUM(a.RVSPAYCNT) RVSPAYCNT ,SUM(a.RVSPAYAMT) RVSPAYAMT 
,SUM(a.RECVAMT+a.RVSRECVAMT) in_tol, SUM(a.PAYAMT+a.RVSPAYAMT) out_tol,SUM((a.RECVAMT+a.RVSRECVAMT)-(a.PAYAMT+a.RVSPAYAMT)) dif_tol   
FROM  RPONCLEARINGTAB a
LEFT JOIN EACH_TXN_CODE T ON a.PCODE = T.EACH_TXN_ID
WHERE a.BIZDATE = '20150316' 
GROUP BY a.CLEARINGPHASE  ,a.BGBK_ID  ,T.EACH_TXN_ID , T.EACH_TXN_NAME
ORDER BY a.BGBK_ID , a.CLEARINGPHASE , T.EACH_TXN_ID , T.EACH_TXN_NAME



--總行GROUP 業務類別版
SELECT
 VARCHAR(a.BGBK_ID) BGBK_ID
, (select coalesce(bgbk_name,'') from bank_group where bgbk_id=a.BGBK_ID) BGBK_NAME
,VARCHAR(a.CLEARINGPHASE) CLEARINGPHASE ,b.BUSINESS_TYPE_ID , b.BUSINESS_TYPE_NAME --業務類別版本
,SUM(a.RECVCNT) RECVCNT , SUM(a.RECVAMT) RECVAMT ,SUM(a.PAYCNT) PAYCNT , SUM(a.PAYAMT ) PAYAMT ,SUM(a.RVSRECVCNT) RVSRECVCNT , SUM(a.RVSRECVAMT) RVSRECVAMT ,SUM(a.RVSPAYCNT) RVSPAYCNT ,SUM(a.RVSPAYAMT) RVSPAYAMT 
,SUM(a.RECVAMT+a.RVSRECVAMT) in_tol, SUM(a.PAYAMT+a.RVSPAYAMT) out_tol,SUM((a.RECVAMT+a.RVSRECVAMT)-(a.PAYAMT+a.RVSPAYAMT)) dif_tol   
FROM  RPONCLEARINGTAB a
LEFT JOIN EACH_TXN_CODE T ON a.PCODE = T.EACH_TXN_ID
LEFT JOIN BUSINESS_TYPE B ON T.BUSINESS_TYPE_ID=B.BUSINESS_TYPE_ID
--WHERE a.BIZDATE = ?   
GROUP BY a.CLEARINGPHASE  ,a.BGBK_ID  ,b.BUSINESS_TYPE_ID , b.BUSINESS_TYPE_NAME
ORDER BY   a.BGBK_ID   ,  a.CLEARINGPHASE , b.BUSINESS_TYPE_ID , b.BUSINESS_TYPE_NAME


--分行GROUP 
SELECT
 VARCHAR(a.BGBK_ID) BGBK_ID
, (select coalesce(bgbk_name,'') from bank_group where bgbk_id=a.BGBK_ID) BGBK_NAME
,a.BRBK_ID 
, (select coalesce(brbk_name,'') from bank_branch where brbk_id=a.BRBK_ID) BRBK_NAME
,VARCHAR(a.CLEARINGPHASE) CLEARINGPHASE ,b.BUSINESS_TYPE_ID , b.BUSINESS_TYPE_NAME
,SUM(a.RECVCNT) RECVCNT , SUM(a.RECVAMT) RECVAMT ,SUM(a.PAYCNT) PAYCNT , SUM(a.PAYAMT ) PAYAMT ,SUM(a.RVSRECVCNT) RVSRECVCNT , SUM(a.RVSRECVAMT) RVSRECVAMT ,SUM(a.RVSPAYCNT) RVSPAYCNT ,SUM(a.RVSPAYAMT) RVSPAYAMT 
,SUM(a.RECVAMT+a.RVSRECVAMT) in_tol, SUM(a.PAYAMT+a.RVSPAYAMT) out_tol,SUM((a.RECVAMT+a.RVSRECVAMT)-(a.PAYAMT+a.RVSPAYAMT)) dif_tol   
FROM  RPONCLEARINGTAB a
LEFT JOIN EACH_TXN_CODE T ON a.PCODE = T.EACH_TXN_ID
LEFT JOIN BUSINESS_TYPE B ON T.BUSINESS_TYPE_ID=B.BUSINESS_TYPE_ID
--WHERE a.BIZDATE = ?   
GROUP BY a.CLEARINGPHASE  ,a.BGBK_ID , a.BRBK_ID ,b.BUSINESS_TYPE_ID , b.BUSINESS_TYPE_NAME
ORDER BY   a.BGBK_ID ,a.BRBK_ID  ,  a.CLEARINGPHASE , b.BUSINESS_TYPE_ID , b.BUSINESS_TYPE_NAME







--20150227前的舊語法

WITH TEMP AS( SELECT  T.BUSINESS_TYPE_ID,B.BUSINESS_TYPE_NAME ,a.BGBK_ID , a.BRBK_ID
		, a.RECVCNT , a.RECVAMT, a.PAYCNT, a.PAYAMT, a.RVSRECVCNT, a.RVSRECVAMT 
		  , a.RVSPAYCNT, a.RVSPAYAMT ,a.RECVAMT+a.RVSRECVAMT in_tol ,a.PAYAMT+a.RVSPAYAMT out_tol 
	 ,((a.RECVAMT+a.RVSRECVAMT)-(a.PAYAMT+a.RVSPAYAMT)) dif_tol 
	 ,a.CLEARINGPHASE 
		 FROM  RPONCLEARINGTAB a
		 JOIN EACH_TXN_CODE T ON a.PCODE = T.EACH_TXN_ID
		JOIN BUSINESS_TYPE B ON T.BUSINESS_TYPE_ID=B.BUSINESS_TYPE_ID 
--WHERE a.BGBK_ID = '0040000'
		) 
		
		 SELECT (a.BUSINESS_TYPE_ID ||'\n'|| a.BUSINESS_TYPE_NAME) BS_ID_NAME , a.CLEARINGPHASE ||'' CLEARINGPHASE 
		 ,COUNT( a.RECVCNT ) RECVCNT ,SUM( a.RECVAMT ) RECVAMT,COUNT( a.PAYCNT ) PAYCNT ,SUM( a.PAYAMT ) PAYAMT 
		,COUNT( a.RVSRECVCNT ) RVSRECVCNT,SUM( a.RVSRECVAMT ) RVSRECVAMT,COUNT( a.RVSPAYCNT ) RVSPAYCNT,SUM( a.RVSPAYAMT ) RVSPAYAMT 
		,SUM( a.RECVAMT+a.RVSRECVAMT) in_tol,SUM( a.PAYAMT+a.RVSPAYAMT) out_tol,SUM((a.RECVAMT+a.RVSRECVAMT)-(a.PAYAMT+a.RVSPAYAMT)) dif_tol  
		FROM  TEMP a
		GROUP BY   a.BUSINESS_TYPE_ID , a.CLEARINGPHASE,a.BUSINESS_TYPE_NAME 
		ORDER BY  a.BUSINESS_TYPE_ID 