--V1.0
WITH TEMP AS (
	SELECT '1' AS ACCTCODE, BIZDATE, CLEARINGPHASE, BRBK_ID, BGBK_ID, TXN_ID, SENDERID, BUSINESS_TYPE_ID, OP_TYPE, BRBK_NAME, BGBK_NAME, OPBK_ID, OPBK_NAME, TXN_NAME, COMPANY_ABBR_NAME, BUSINESS_TYPE_NAME,
	('0'||VARCHAR(CAST(YYYYMM AS INT) - 191100)) AS YYYYMM, CNT, AMT, 0 AS RVSCNT, 0 AS RVSAMT     
	FROM RPCLEARFEETAB
	WHERE COALESCE(CNT,0) <> 0
    AND YYYYMM = '201504'
	UNION ALL
	SELECT '0' AS ACCTCODE, BIZDATE, CLEARINGPHASE, BRBK_ID, BGBK_ID, TXN_ID, SENDERID, BUSINESS_TYPE_ID, OP_TYPE, BRBK_NAME, BGBK_NAME, OPBK_ID, OPBK_NAME, TXN_NAME, COMPANY_ABBR_NAME, BUSINESS_TYPE_NAME,
	('0'||VARCHAR(CAST(YYYYMM AS INT) - 191100)) AS YYYYMM, 0 AS CNT, 0 AS AMT, RVSCNT, RVSAMT
	FROM RPCLEARFEETAB
	WHERE COALESCE(RVSCNT,0) <> 0
	AND YYYYMM = '201504'
)

SELECT
YYYYMM,
(CASE A.ACCTCODE WHEN '0' THEN '沖正' ELSE '一般' END) AS ACCTCODE,
A.TXN_ID || COALESCE((SELECT '-' || TXN_NAME FROM TXN_CODE WHERE TXN_ID = A.TXN_ID),'') AS TXN_ID,
RTRIM(A.SENDERID) || COALESCE((SELECT '-' || COMPANY_ABBR_NAME FROM (SELECT COMPANY_ID, TXN_ID, SND_BRBK_ID, COMPANY_ABBR_NAME FROM SD_COMPANY_PROFILE UNION SELECT COMPANY_ID, TXN_ID, SND_BRBK_ID, COMPANY_ABBR_NAME FROM SC_COMPANY_PROFILE) WHERE COMPANY_ID = A.SENDERID AND TXN_ID = A.TXN_ID FETCH FIRST 1 ROWS ONLY),'') AS SENDERID
,COALESCE((SELECT SUM((CASE A.ACCTCODE WHEN '1' THEN COALESCE(CNT,0) ELSE COALESCE(RVSCNT,0) END)) FROM TEMP WHERE YYYYMM = A.YYYYMM AND ACCTCODE = A.ACCTCODE AND TXN_ID = A.TXN_ID AND COALESCE(SENDERID,'') = A.SENDERID AND OP_TYPE = 'S'),0) AS FIRECOUNT
,COALESCE((SELECT SUM((CASE A.ACCTCODE WHEN '1' THEN COALESCE(AMT,0) ELSE COALESCE(RVSAMT,0) END)) FROM TEMP WHERE YYYYMM = A.YYYYMM AND ACCTCODE = A.ACCTCODE AND TXN_ID = A.TXN_ID AND COALESCE(SENDERID,'') = A.SENDERID AND OP_TYPE = 'S'),0) AS FIREAMT
,COALESCE((SELECT SUM((CASE A.ACCTCODE WHEN '1' THEN COALESCE(CNT,0) ELSE COALESCE(RVSCNT,0) END)) FROM TEMP WHERE YYYYMM = A.YYYYMM AND ACCTCODE = A.ACCTCODE AND TXN_ID = A.TXN_ID AND COALESCE(SENDERID,'') = A.SENDERID AND OP_TYPE = 'O'),0) AS DEBITCOUNT
,COALESCE((SELECT SUM((CASE A.ACCTCODE WHEN '1' THEN COALESCE(AMT,0) ELSE COALESCE(RVSAMT,0) END)) FROM TEMP WHERE YYYYMM = A.YYYYMM AND ACCTCODE = A.ACCTCODE AND TXN_ID = A.TXN_ID AND COALESCE(SENDERID,'') = A.SENDERID AND OP_TYPE = 'O'),0) AS DEBITAMT
,COALESCE((SELECT SUM((CASE A.ACCTCODE WHEN '1' THEN COALESCE(CNT,0) ELSE COALESCE(RVSCNT,0) END)) FROM TEMP WHERE YYYYMM = A.YYYYMM AND ACCTCODE = A.ACCTCODE AND TXN_ID = A.TXN_ID AND COALESCE(SENDERID,'') = A.SENDERID AND OP_TYPE = 'I'),0) AS SAVECOUNT
,COALESCE((SELECT SUM((CASE A.ACCTCODE WHEN '1' THEN COALESCE(AMT,0) ELSE COALESCE(RVSAMT,0) END)) FROM TEMP WHERE YYYYMM = A.YYYYMM AND ACCTCODE = A.ACCTCODE AND TXN_ID = A.TXN_ID AND COALESCE(SENDERID,'') = A.SENDERID AND OP_TYPE = 'I'),0) AS SAVEAMT
FROM (
    SELECT YYYYMM, ACCTCODE, TXN_ID, COALESCE(SENDERID,'') AS SENDERID FROM TEMP GROUP BY YYYYMM, ACCTCODE, TXN_ID, SENDERID
) AS A
ORDER BY A.ACCTCODE DESC, A.TXN_ID, A.SENDERID