--V1.0
--調帳金額
SELECT COALESCE(SUM(D.FEE),0) AS FEE FROM (
     SELECT BFA.YYYYMM, BFA.BRBK_ID, SUM(FEE) AS FEE,
     COALESCE(BR.BGBK_ID,(CASE BFA.BRBK_ID WHEN '0188888' THEN '0188888' ELSE '' END)) AS BGBK_ID
     FROM BRBK_FEE_ADJ AS BFA LEFT JOIN BANK_BRANCH AS BR ON BFA.BRBK_ID = BR.BRBK_ID
     WHERE COALESCE(BFA.ACTIVE_DATE,'') <> ''
     GROUP BY BFA.YYYYMM, BR.BGBK_ID, BFA.BRBK_ID 
) AS D LEFT JOIN BANK_GROUP AS BG ON D.BGBK_ID = BG.BGBK_ID 
WHERE  D.YYYYMM = '010404'  AND  BG.OPBK_ID = '4530000'

SELECT VARCHAR(SUBSTR(TRANS_DATE(BIZDATE,'T','/'),2,9)) AS BIZDATE
,COALESCE((SELECT SUM(COALESCE(CNT,0))+SUM(COALESCE(RVSCNT,0)) FROM RPCLEARFEETAB WHERE BIZDATE = A.BIZDATE AND OPBK_ID = A.OPBK_ID AND BGBK_ID = A.BGBK_ID AND BRBK_ID = A.BRBK_ID AND OP_TYPE = 'S'),0) AS FIRECOUNT
,COALESCE((SELECT SUM(COALESCE(AMT,0))+SUM(COALESCE(RVSAMT,0)) FROM RPCLEARFEETAB WHERE BIZDATE = A.BIZDATE AND OPBK_ID = A.OPBK_ID AND BGBK_ID = A.BGBK_ID AND BRBK_ID = A.BRBK_ID AND OP_TYPE = 'S'),0) AS FIREAMT
,COALESCE((SELECT SUM(COALESCE(CNT,0))+SUM(COALESCE(RVSCNT,0)) FROM RPCLEARFEETAB WHERE BIZDATE = A.BIZDATE AND OPBK_ID = A.OPBK_ID AND BGBK_ID = A.BGBK_ID AND BRBK_ID = A.BRBK_ID AND OP_TYPE = 'O'),0) AS DEBITCOUNT
,COALESCE((SELECT SUM(COALESCE(AMT,0))+SUM(COALESCE(RVSAMT,0)) FROM RPCLEARFEETAB WHERE BIZDATE = A.BIZDATE AND OPBK_ID = A.OPBK_ID AND BGBK_ID = A.BGBK_ID AND BRBK_ID = A.BRBK_ID AND OP_TYPE = 'O'),0) AS DEBITAMT
,COALESCE((SELECT SUM(COALESCE(CNT,0))+SUM(COALESCE(RVSCNT,0)) FROM RPCLEARFEETAB WHERE BIZDATE = A.BIZDATE AND OPBK_ID = A.OPBK_ID AND BGBK_ID = A.BGBK_ID AND BRBK_ID = A.BRBK_ID AND OP_TYPE = 'I'),0) AS SAVECOUNT
,COALESCE((SELECT SUM(COALESCE(AMT,0))+SUM(COALESCE(RVSAMT,0)) FROM RPCLEARFEETAB WHERE BIZDATE = A.BIZDATE AND OPBK_ID = A.OPBK_ID AND BGBK_ID = A.BGBK_ID AND BRBK_ID = A.BRBK_ID AND OP_TYPE = 'I'),0) AS SAVEAMT
FROM RPCLEARFEETAB A
WHERE YYYYMM = '201503' AND A.OPBK_ID = '9970018' AND BGBK_ID = '1610000' AND BRBK_ID = '1610000'
GROUP BY BIZDATE, OPBK_ID, BGBK_ID, BRBK_ID
ORDER BY BIZDATE