INSERT INTO "EACHUSER"."EACH_BATCH_NOTIFY"("BIZDATE", "CLEARINGPHASE", "CLEAR_NOTIFY", "RPT_NOTIFY")
VALUES('20150415', '02', 'Y', 'Y')
GO
INSERT INTO "EACHUSER"."EACH_BATCH_NOTIFY"("BIZDATE", "CLEARINGPHASE", "CLEAR_NOTIFY", "RPT_NOTIFY")
VALUES('20150415', '01', 'Y', 'Y')
GO
