--V3.0
SELECT  
VARCHAR_FORMAT(C.NEWTXDT, 'YYYY-MM-DD HH24:MI:SS') AS TXDT, 
C.PCODE || '-' || COALESCE((SELECT EACH_TXN_NAME FROM EACH_TXN_CODE WHERE EACH_TXN_ID = C.PCODE),'') AS PCODE, 
C.SENDERBANKID || '-' || (SELECT COALESCE(BRBK_NAME,'') FROM BANK_BRANCH WHERE BRBK_ID = C.SENDERBANKID) AS SENDERBANKID, 
C.OUTBANKID || '-' || (SELECT COALESCE(BRBK_NAME,'') FROM BANK_BRANCH WHERE BRBK_ID = C.OUTBANKID) AS OUTBANKID, 
C.INBANKID || '-' || (SELECT COALESCE(BRBK_NAME,'') FROM BANK_BRANCH WHERE BRBK_ID = C.INBANKID) AS INBANKID, 
C.NEWTXAMT AS TXAMT, C.OUTACCTNO, C.INACCTNO, C.STAN, C.TXDATE, UPDATEDT, BIZDATE, CLEARINGPHASE,
C.SENDERID || '-' || COALESCE((SELECT COMPANY_ABBR_NAME FROM (SELECT COMPANY_ID, TXN_ID, SND_BRBK_ID, COMPANY_ABBR_NAME FROM SD_COMPANY_PROFILE UNION SELECT COMPANY_ID, TXN_ID, SND_BRBK_ID, COMPANY_ABBR_NAME FROM SC_COMPANY_PROFILE) WHERE COMPANY_ID = C.SENDERID AND TXN_ID = C.TXID AND SND_BRBK_ID = C.SENDERBANKID),'') AS SENDERID,
C.TXID || '-' || COALESCE((SELECT TXN_NAME FROM TXN_CODE WHERE TXN_ID = C.TXID),'') AS TXID,
(CASE C.RESULTSTATUS WHEN 'A' THEN '成功' WHEN 'R' THEN '失敗' ELSE (CASE SENDERSTATUS WHEN '1' THEN '處理中' ELSE '未完成' END) END) AS RESP
FROM (
    SELECT ROWNUMBER() OVER() AS ROWNUMBER,
    NEWTXDT, PCODE, SENDERBANKID, OUTBANKID, INBANKID, NEWTXAMT, OUTACCTNO, INACCTNO, STAN, TXDATE, NEWRESULT, UPDATEDT,
    (CASE WHEN RESULTSTATUS = 'P' AND NEWRESULT = 'R' THEN '0' ELSE '1' END) AS ACCTCODE, BIZDATE, CLEARINGPHASE, TXID,
    SENDERID, RECEIVERID, SENDERACQUIRE, OUTACQUIRE, INACQUIRE, SENDERHEAD, OUTHEAD, INHEAD, RESULTSTATUS, SENDERSTATUS
    FROM VW_ONBLOCKTAB A
    WHERE  (BIZDATE >= '20150301' AND BIZDATE <= '20150313')  
    AND  (SENDERACQUIRE = '4530000' OR INACQUIRE = '4530000' OR OUTACQUIRE = '4530000')  
    AND  (SENDERHEAD = '4530000' OR INHEAD = '4530000' OR OUTHEAD = '4530000')  
    AND  (SENDERBANKID = '4530000' OR INBANKID = '4530000' OR OUTBANKID = '4530000')  
    AND  CLEARINGPHASE = '01' AND SUBSTR(PCODE,1,2) LIKE SUBSTR('2100',1,2)
) AS C WHERE ROWNUMBER >= 1 AND ROWNUMBER <= 10
ORDER BY NEWTXDT asc

--V2.0
SELECT 
VARCHAR_FORMAT(C.NEWTXDT, 'YYYY-MM-DD HH24:MI:SS') AS TXDT, 
C.PCODE || '-' || COALESCE(C.EACH_TXN_NAME,'') AS PCODE, 
C.SENDERBANKID || '-' || (SELECT COALESCE(BRBK_NAME,'') FROM BANK_BRANCH WHERE BRBK_ID = C.SENDERBANKID) AS SENDERBANKID, 
C.OUTBANKID || '-' || (SELECT COALESCE(BRBK_NAME,'') FROM BANK_BRANCH WHERE BRBK_ID = C.OUTBANKID) AS OUTBANKID, 
C.INBANKID || '-' || (SELECT COALESCE(BRBK_NAME,'') FROM BANK_BRANCH WHERE BRBK_ID = C.INBANKID) AS INBANKID, 
C.NEWTXAMT AS TXAMT, C.OUTACCTNO, C.INACCTNO, C.STAN, C.TXDATE, UPDATEDT, BIZDATE, CLEARINGPHASE, 
(CASE C.NEWRESULT WHEN 'A' THEN '成功' WHEN 'R' THEN '失敗' ELSE '未完成' END) AS RESP, 
(CASE ACCTCODE WHEN '0' THEN '調整' ELSE '一般' END) AS ACCTCODE 
FROM ( 
    SELECT * FROM (     
        SELECT ROWNUMBER() OVER( ORDER BY NEWTXDT asc) AS ROWNUMBER, A.*, B.EACH_TXN_NAME 
        FROM (     
            SELECT NEWTXDT, PCODE, SENDERBANKID, OUTBANKID, INBANKID, NEWTXAMT, OUTACCTNO, INACCTNO, STAN, TXDATE, NEWRESULT, UPDATEDT,     
            (CASE WHEN RESULTSTATUS = 'P' AND NEWRESULT = 'R' THEN '0' ELSE '1' END) AS ACCTCODE, BIZDATE, CLEARINGPHASE,     
            SENDERID, RECEIVERID, SENDERACQUIRE, OUTACQUIRE, INACQUIRE, SENDERHEAD, OUTHEAD, INHEAD, RESULTSTATUS     
            FROM VW_ONBLOCKTAB WHERE  (BIZDATE >= '20150302' AND BIZDATE <= '20150302')     
            UNION ALL     
            SELECT NEWTXDT, PCODE, SENDERBANKID, OUTBANKID, INBANKID, NEWTXAMT, OUTACCTNO, INACCTNO, STAN, TXDATE, NEWRESULT, UPDATEDT,     
            (CASE WHEN RESULTSTATUS = 'P' AND NEWRESULT = 'R' THEN '0' ELSE '1' END) AS ACCTCODE, NEWBIZDATE, NEWCLRPHASE,     
            SENDERID, RECEIVERID, SENDERACQUIRE, OUTACQUIRE, INACQUIRE, SENDERHEAD, OUTHEAD, INHEAD, RESULTSTATUS     
            FROM VW_ONPENDING_EC WHERE  (NEWBIZDATE >= '20150302' AND NEWBIZDATE <= '20150302') 
        ) AS A LEFT JOIN EACH_TXN_CODE B ON A.PCODE = B.EACH_TXN_ID 
    ) WHERE ROWNUMBER >= 1 AND ROWNUMBER <= 10 
) AS C 

--V1.0
SELECT 
VARCHAR_FORMAT(A.NEWTXDT, 'YYYY-MM-DD HH24:MI:SS') AS TXDT, --������/�ɶ�
A.PCODE || '-' || COALESCE(B.EACH_TXN_NAME,'') AS PCODE, --������O 
A.SENDERBANKID || '-' || (SELECT COALESCE(BRBK_NAME,'') FROM BANK_BRANCH WHERE BRBK_ID = A.SENDERBANKID) AS SENDERBANKID, --�o�ʳ��
A.OUTBANKID || '-' || (SELECT COALESCE(BRBK_NAME,'') FROM BANK_BRANCH WHERE BRBK_ID = A.OUTBANKID) AS OUTBANKID, --���ڳ��
A.INBANKID || '-' || (SELECT COALESCE(BRBK_NAME,'') FROM BANK_BRANCH WHERE BRBK_ID = A.INBANKID) AS INBANKID, --�J�b���
A.NEWTXAMT AS TXAMT, --������B
A.OUTACCTNO, A.INACCTNO, --���ڡB�J�b�b��
A.STAN, A.TXDATE, --�t�ΰl�ܧǸ��B������
(CASE A.NEWRESULT WHEN 'A' THEN '���\' WHEN 'R' THEN '����' ELSE '������' END) AS RESP, UPDATEDT --������G
FROM VW_ONBLOCKTAB A LEFT JOIN EACH_TXN_CODE B ON B.EACH_TXN_ID = A.PCODE
WHERE  
(A.BIZDATE >= '20150213' AND A.BIZDATE <= '20150216') --��~��
AND  A.STAN = '0040100892' --����l�ܧǸ� 
AND  A.SENDERID = '97162178' --�o�ʪ̲νs 
AND  A.INACCTNO = '8000800080008000' --�J�b�b��  
AND  A.NEWTXAMT = ISNUMERIC('3000') --������B 
AND  A.SENDERACQUIRE = '0040000' --�o�ʦ���ݾާ@�� (�̬d�ߨ����ܰ�) 
AND  A.SENDERHEAD = '0040000' --�o�ʦ�����`�� (�̬d�ߨ����ܰ�)  
AND  A.SENDERBANKID = '0040037' --�o�ʦ�N�� (�̬d�ߨ����ܰ�)   
AND  A.CLEARINGPHASE = '01' --�M�ⶥ�q 
AND  B.BUSINESS_TYPE_ID = '2100' --�~�����O 
AND  (A.NEWRESULT = 'A') --������G