--V4.0
WITH TEMP AS (
    SELECT PCODE, SENDERBANKID, OUTBANKID, INBANKID,
    (CASE '01' WHEN '' THEN NEWSENDERFEE ELSE SENDERFEE END) AS NEWSENDERFEE,
    (CASE '01' WHEN '' THEN NEWOUTFEE ELSE OUTFEE END) AS NEWOUTFEE,
    (CASE '01' WHEN '' THEN NEWINFEE ELSE INFEE END) AS NEWINFEE,
    (CASE WHEN (CASE '01' WHEN '' THEN RESULTSTATUS ELSE GETFIRSTSTATUS(TXDATE, STAN, '20150311', '') END) <> 'R' THEN '1' ELSE (CASE ACCTCODE WHEN '0' THEN '0' ELSE '1' END) END) AS ACCTCODE
    FROM VW_ONBLOCKTAB
    WHERE NEWRESULT <> 'R' 
    AND (CASE '' WHEN '' THEN RESULTSTATUS ELSE GETFIRSTSTATUS(TXDATE, STAN, '20150311', '') END) <> 'R'
    AND SENDERSTATUS <> '1' AND  PCODE = '2501'  
    AND  (SENDERACQUIRE = '9970018' OR OUTACQUIRE = '9970018' OR INACQUIRE = '9970018')  
    AND  (SENDERHEAD = '1610000' OR OUTHEAD = '1610000' OR INHEAD = '1610000')  
    AND  (SENDERBANKID = '1610022' OR OUTBANKID = '1610022' OR INBANKID = '1610022')  
    AND  CLEARINGPHASE = '01'  AND  BIZDATE >= '20150225'  AND  BIZDATE <= '20150311'     
    UNION ALL
    SELECT PCODE, SENDERBANKID, OUTBANKID, INBANKID, NEWSENDERFEE, NEWOUTFEE, NEWINFEE, ACCTCODE     
    FROM VW_ONPENDING_EC 	
    WHERE  PCODE = '2501'  
    AND  (SENDERACQUIRE = '9970018' OR OUTACQUIRE = '9970018' OR INACQUIRE = '9970018')  
    AND  (SENDERHEAD = '1610000' OR OUTHEAD = '1610000' OR INHEAD = '1610000')  
    AND  (SENDERBANKID = '1610022' OR OUTBANKID = '1610022' OR INBANKID = '1610022')  
    AND  NEWCLRPHASE = '01'  AND  NEWBIZDATE >= '20150225'  AND  NEWBIZDATE <= '20150311' 
) 
SELECT 
(A.BGBK_ID || '-' || A.BGBK_NAME ) AS BGBK_ID_NAME, (A.BANKID || '-' || A.BRBK_NAME) AS BANKID, A.PCODE, 
(CASE A.ACCTCODE WHEN '0' THEN '調整' ELSE '一般' END) AS ACCTCODE, 
(SELECT COUNT(*) FROM TEMP WHERE SENDERBANKID = A.BANKID AND PCODE = A.PCODE AND ACCTCODE = A.ACCTCODE) AS FIRECOUNT, 
COALESCE((SELECT SUM(NEWSENDERFEE) FROM TEMP WHERE SENDERBANKID = A.BANKID AND PCODE = A.PCODE AND ACCTCODE = A.ACCTCODE),0) AS FIREAMT, 
(SELECT COUNT(*) FROM TEMP WHERE OUTBANKID = A.BANKID AND PCODE = A.PCODE AND ACCTCODE = A.ACCTCODE) AS DEBITCOUNT, 
COALESCE((SELECT SUM(NEWOUTFEE) FROM TEMP WHERE OUTBANKID = A.BANKID AND PCODE = A.PCODE AND ACCTCODE = A.ACCTCODE),0) AS DEBITAMT, 
(SELECT COUNT(*) FROM TEMP WHERE INBANKID = A.BANKID AND PCODE = A.PCODE AND ACCTCODE = A.ACCTCODE) AS SAVECOUNT, 
COALESCE((SELECT SUM(NEWINFEE) FROM TEMP WHERE INBANKID = A.BANKID AND PCODE = A.PCODE AND ACCTCODE = A.ACCTCODE),0) AS SAVEAMT , 
A.BGBK_ID, A.BGBK_NAME, A.OPBK_ID, A.OPBK_NAME 
FROM (
     SELECT ROWNUMBER() OVER(ORDER BY BANKID, PCODE, ACCTCODE) AS ROWNUMBER, T.* FROM (
         SELECT * FROM (
             SELECT * FROM (
                 SELECT SENDERBANKID AS BANKID, PCODE, (CASE ACCTCODE WHEN '0' THEN '0' ELSE '1' END) AS ACCTCODE FROM TEMP GROUP BY SENDERBANKID, PCODE, ACCTCODE
                 UNION     SELECT OUTBANKID, PCODE, (CASE ACCTCODE WHEN '0' THEN '0' ELSE '1' END) AS ACCTCODE FROM TEMP GROUP BY OUTBANKID, PCODE, ACCTCODE
                 UNION     SELECT INBANKID, PCODE, (CASE ACCTCODE WHEN '0' THEN '0' ELSE '1' END) AS ACCTCODE FROM TEMP GROUP BY INBANKID, PCODE, ACCTCODE
             )  WHERE  PCODE = '2501'  AND  BANKID = '1610022'
         ) AS X LEFT JOIN (
         	 SELECT BR.BRBK_ID, BR.BRBK_NAME,
			 BR.BGBK_ID, (SELECT BG.BGBK_NAME FROM BANK_GROUP AS BG WHERE BG.BGBK_ID = OP.BGBK_ID) AS BGBK_NAME,
			 OP.OPBK_ID, (SELECT BG.BGBK_NAME FROM BANK_GROUP AS BG WHERE BG.BGBK_ID = OP.OPBK_ID) AS OPBK_NAME
			 FROM BANK_BRANCH AS BR LEFT JOIN (
				 SELECT DISTINCT BGBK_ID, OPBK_ID
				 FROM BANK_OPBK
			 ) AS OP ON BR.BGBK_ID = OP.BGBK_ID
			 WHERE OP.OPBK_ID = '9970018'  AND OP.BGBK_ID = '1610000'
         ) AS Y ON X.BANKID = Y.BRBK_ID
         WHERE  Y.OPBK_ID = '9970018'  AND  Y.BGBK_ID = '1610000'  AND  Y.BRBK_ID = '1610022'
     ) AS T 
) AS A WHERE ROWNUMBER >= 1 AND ROWNUMBER <= 10  
ORDER BY BANKID, PCODE, ACCTCODE asc

--V3.0
WITH TEMP AS (
    SELECT PCODE, SENDERBANKID, OUTBANKID, INBANKID,
    (CASE '01' WHEN '' THEN NEWSENDERFEE ELSE SENDERFEE END) AS NEWSENDERFEE,
    (CASE '01' WHEN '' THEN NEWOUTFEE ELSE OUTFEE END) AS NEWOUTFEE,
    (CASE '01' WHEN '' THEN NEWINFEE ELSE INFEE END) AS NEWINFEE,
    (CASE WHEN (CASE '01' WHEN '' THEN RESULTSTATUS ELSE GETFIRSTSTATUS(TXDATE, STAN, '20150311', '') END) <> 'R' THEN '1' ELSE (CASE ACCTCODE WHEN '0' THEN '0' ELSE '1' END) END) AS ACCTCODE
    FROM VW_ONBLOCKTAB
    WHERE NEWRESULT <> 'R' 
    AND (CASE '' WHEN '' THEN RESULTSTATUS ELSE GETFIRSTSTATUS(TXDATE, STAN, '20150311', '') END) <> 'R'
    AND SENDERSTATUS <> '1' AND  PCODE = '2501'  
    AND  (SENDERACQUIRE = '9970018' OR OUTACQUIRE = '9970018' OR INACQUIRE = '9970018')  
    AND  (SENDERHEAD = '1610000' OR OUTHEAD = '1610000' OR INHEAD = '1610000')  
    AND  (SENDERBANKID = '1610022' OR OUTBANKID = '1610022' OR INBANKID = '1610022')  
    AND  CLEARINGPHASE = '01'  AND  BIZDATE >= '20150225'  AND  BIZDATE <= '20150311'     
    UNION ALL
    SELECT PCODE, SENDERBANKID, OUTBANKID, INBANKID, NEWSENDERFEE, NEWOUTFEE, NEWINFEE, ACCTCODE     
    FROM VW_ONPENDING_EC 	
    WHERE  PCODE = '2501'  
    AND  (SENDERACQUIRE = '9970018' OR OUTACQUIRE = '9970018' OR INACQUIRE = '9970018')  
    AND  (SENDERHEAD = '1610000' OR OUTHEAD = '1610000' OR INHEAD = '1610000')  
    AND  (SENDERBANKID = '1610022' OR OUTBANKID = '1610022' OR INBANKID = '1610022')  
    AND  NEWCLRPHASE = '01'  AND  NEWBIZDATE >= '20150225'  AND  NEWBIZDATE <= '20150311' 
) 
SELECT 
(A.BGBK_ID || '-' || A.BGBK_NAME ) AS BGBK_ID_NAME, (A.BANKID || '-' || A.BRBK_NAME) AS BANKID, A.PCODE, 
(CASE A.ACCTCODE WHEN '0' THEN '調整' ELSE '一般' END) AS ACCTCODE, 
(SELECT COUNT(*) FROM TEMP WHERE SENDERBANKID = A.BANKID AND PCODE = A.PCODE AND ACCTCODE = A.ACCTCODE) AS FIRECOUNT, 
COALESCE((SELECT SUM(NEWSENDERFEE) FROM TEMP WHERE SENDERBANKID = A.BANKID AND PCODE = A.PCODE AND ACCTCODE = A.ACCTCODE),0) AS FIREAMT, 
(SELECT COUNT(*) FROM TEMP WHERE OUTBANKID = A.BANKID AND PCODE = A.PCODE AND ACCTCODE = A.ACCTCODE) AS DEBITCOUNT, 
COALESCE((SELECT SUM(NEWOUTFEE) FROM TEMP WHERE OUTBANKID = A.BANKID AND PCODE = A.PCODE AND ACCTCODE = A.ACCTCODE),0) AS DEBITAMT, 
(SELECT COUNT(*) FROM TEMP WHERE INBANKID = A.BANKID AND PCODE = A.PCODE AND ACCTCODE = A.ACCTCODE) AS SAVECOUNT, 
COALESCE((SELECT SUM(NEWINFEE) FROM TEMP WHERE INBANKID = A.BANKID AND PCODE = A.PCODE AND ACCTCODE = A.ACCTCODE),0) AS SAVEAMT , 
A.BGBK_ID, A.BGBK_NAME, A.OPBK_ID, A.OPBK_NAME 
FROM (
     SELECT ROWNUMBER() OVER(ORDER BY BANKID, PCODE, ACCTCODE) AS ROWNUMBER, T.* FROM (
         SELECT * FROM (
             SELECT * FROM (
                 SELECT SENDERBANKID AS BANKID, PCODE, (CASE ACCTCODE WHEN '0' THEN '0' ELSE '1' END) AS ACCTCODE FROM TEMP GROUP BY SENDERBANKID, PCODE, ACCTCODE
                 UNION     SELECT OUTBANKID, PCODE, (CASE ACCTCODE WHEN '0' THEN '0' ELSE '1' END) AS ACCTCODE FROM TEMP GROUP BY OUTBANKID, PCODE, ACCTCODE
                 UNION     SELECT INBANKID, PCODE, (CASE ACCTCODE WHEN '0' THEN '0' ELSE '1' END) AS ACCTCODE FROM TEMP GROUP BY INBANKID, PCODE, ACCTCODE
             )  WHERE  PCODE = '2501'  AND  BANKID = '1610022'
         ) AS X LEFT JOIN (
             SELECT BR.BRBK_ID, BR.BRBK_NAME, BG.BGBK_ID, BG.BGBK_NAME, BG.OPBK_ID, OP.BGBK_NAME AS OPBK_NAME
             FROM BANK_BRANCH BR LEFT JOIN BANK_GROUP BG ON BR.BGBK_ID = BG.BGBK_ID
             LEFT JOIN BANK_GROUP OP ON BG.OPBK_ID = OP.BGBK_ID
             WHERE  OP.OPBK_ID = '9970018'  AND  BG.BGBK_ID = '1610000'
         ) AS Y ON X.BANKID = Y.BRBK_ID
         WHERE  Y.OPBK_ID = '9970018'  AND  Y.BGBK_ID = '1610000'  AND  Y.BRBK_ID = '1610022'
     ) AS T 
) AS A WHERE ROWNUMBER >= 1 AND ROWNUMBER <= 10  
ORDER BY BANKID, PCODE, ACCTCODE asc

--V2.0
WITH TEMP AS (
    SELECT PCODE, SENDERBANKID, OUTBANKID, INBANKID, 
    (CASE '01' WHEN '' THEN NEWSENDERFEE ELSE SENDERFEE END) AS NEWSENDERFEE,
    (CASE '01' WHEN '' THEN NEWOUTFEE ELSE OUTFEE END) AS NEWOUTFEE, 
    (CASE '01' WHEN '' THEN NEWINFEE ELSE INFEE END) AS NEWINFEE, 
    (CASE ACCTCODE WHEN '0' THEN '0' ELSE '1' END) AS ACCTCODE
    FROM VW_ONBLOCKTAB
  	WHERE  BIZDATE >= '20150225'  AND  BIZDATE <= '20150225'  AND  CLEARINGPHASE = '01'
    UNION ALL
    SELECT PCODE, SENDERBANKID, OUTBANKID, INBANKID, NEWSENDERFEE, NEWOUTFEE, NEWINFEE, ACCTCODE
    FROM VW_ONPENDING_EC
    WHERE NEWBIZDATE >= '20150225' AND NEWBIZDATE <= '20150225' AND NEWCLRPHASE = '01'
) 
SELECT * FROM ( 
    SELECT ROWNUMBER() OVER( ORDER BY BANKID, PCODE, ACCTCODE asc) AS ROWNUMBER, 
    (B.BGBK_ID || '-' || B.BGBK_NAME ) AS BGBK_ID_NAME, (A.BANKID || '-' || B.BRBK_NAME) AS BANKID, A.PCODE, 
    (CASE A.ACCTCODE WHEN '0' THEN '調整' ELSE '一般' END) AS ACCTCODE, 
    (SELECT COUNT(*) FROM TEMP WHERE SENDERBANKID = A.BANKID AND PCODE = A.PCODE AND ACCTCODE = A.ACCTCODE) AS FIRECOUNT, 
    COALESCE((SELECT SUM(NEWSENDERFEE) FROM TEMP WHERE SENDERBANKID = A.BANKID AND PCODE = A.PCODE AND ACCTCODE = A.ACCTCODE),0) AS FIREAMT, 
    (SELECT COUNT(*) FROM TEMP WHERE OUTBANKID = A.BANKID AND PCODE = A.PCODE AND ACCTCODE = A.ACCTCODE) AS DEBITCOUNT, 
    COALESCE((SELECT SUM(NEWOUTFEE) FROM TEMP WHERE OUTBANKID = A.BANKID AND PCODE = A.PCODE AND ACCTCODE = A.ACCTCODE),0) AS DEBITAMT, 
    (SELECT COUNT(*) FROM TEMP WHERE INBANKID = A.BANKID AND PCODE = A.PCODE AND ACCTCODE = A.ACCTCODE) AS SAVECOUNT, 
    COALESCE((SELECT SUM(NEWINFEE) FROM TEMP WHERE INBANKID = A.BANKID AND PCODE = A.PCODE AND ACCTCODE = A.ACCTCODE),0) AS SAVEAMT , 
    B.BGBK_ID, B.BGBK_NAME, B.OPBK_ID, B.OPBK_NAME 
    FROM (
         SELECT SENDERBANKID AS BANKID, PCODE, (CASE ACCTCODE WHEN '0' THEN '0' ELSE '1' END) AS ACCTCODE FROM TEMP GROUP BY SENDERBANKID, PCODE, ACCTCODE
         UNION     SELECT OUTBANKID, PCODE, (CASE ACCTCODE WHEN '0' THEN '0' ELSE '1' END) AS ACCTCODE FROM TEMP GROUP BY OUTBANKID, PCODE, ACCTCODE
         UNION     SELECT INBANKID, PCODE, (CASE ACCTCODE WHEN '0' THEN '0' ELSE '1' END) AS ACCTCODE FROM TEMP GROUP BY INBANKID, PCODE, ACCTCODE 
    ) AS A LEFT JOIN (
        SELECT BR.BRBK_ID, BR.BRBK_NAME, BG.BGBK_ID, BG.BGBK_NAME, BG.OPBK_ID, OP.BGBK_NAME AS OPBK_NAME
        FROM BANK_BRANCH BR LEFT JOIN BANK_GROUP BG ON BR.BGBK_ID = BG.BGBK_ID
        LEFT JOIN BANK_GROUP OP ON BG.OPBK_ID = OP.BGBK_ID 
    ) AS B ON A.BANKID = B.BRBK_ID 
    WHERE  A.PCODE = '2501'  AND  B.OPBK_ID = '9970018'  AND  B.BGBK_ID = '1610000'  AND  A.BANKID = '1610022'  
) AS TEMP_ WHERE ROWNUMBER >= 1 AND ROWNUMBER <= 10

--V1.0
WITH TEMP AS ( 	
    SELECT PCODE, SENDERBANKID, OUTBANKID, INBANKID, NEWSENDERFEE, NEWOUTFEE, NEWINFEE     
    FROM VW_ONBLOCKTAB     
    WHERE NEWRESULT = 'A' 
    AND  BIZDATE >= '20150213' --��~��_ 
    AND  BIZDATE <= '20150216' --��~�騴 
    AND  CLEARINGPHASE = '01' --�M�ⶥ�q
)
SELECT
(B.BGBK_ID || '-' || B.BGBK_NAME ) AS BGBK_ID_NAME, --�`��N��
(A.BANKID || '-' || B.BRBK_NAME) AS BANKID, --����N��
A.PCODE, --������O
(SELECT COUNT(*) FROM TEMP WHERE SENDERBANKID = A.BANKID AND PCODE = A.PCODE) AS FIRECOUNT, --�o�ʳ�쵧��
COALESCE((SELECT SUM(NEWSENDERFEE) FROM TEMP WHERE SENDERBANKID = A.BANKID AND PCODE = A.PCODE),0) AS FIREAMT, --�o�ʳ����B
(SELECT COUNT(*) FROM TEMP WHERE OUTBANKID = A.BANKID AND PCODE = A.PCODE) AS DEBITCOUNT, --���ڳ�쵧��
COALESCE((SELECT SUM(NEWOUTFEE) FROM TEMP WHERE OUTBANKID = A.BANKID AND PCODE = A.PCODE),0) AS DEBITAMT, --���ڳ����B
(SELECT COUNT(*) FROM TEMP WHERE INBANKID = A.BANKID AND PCODE = A.PCODE) AS SAVECOUNT, --�J�b��쵧��
COALESCE((SELECT SUM(NEWINFEE) FROM TEMP WHERE INBANKID = A.BANKID AND PCODE = A.PCODE),0) AS SAVEAMT, --�J�b�����B 
B.BGBK_ID, B.BGBK_NAME, B.OPBK_ID, B.OPBK_NAME 
FROM (
    SELECT SENDERBANKID AS BANKID, PCODE FROM VW_ONBLOCKTAB GROUP BY SENDERBANKID, PCODE
    UNION     SELECT OUTBANKID, PCODE FROM VW_ONBLOCKTAB GROUP BY OUTBANKID, PCODE
    UNION     SELECT INBANKID, PCODE FROM VW_ONBLOCKTAB GROUP BY INBANKID, PCODE 
) AS A LEFT JOIN ( 	
    SELECT BR.BRBK_ID, BR.BRBK_NAME, BG.BGBK_ID, BG.BGBK_NAME, BG.OPBK_ID, OP.BGBK_NAME AS OPBK_NAME 	
    FROM BANK_BRANCH BR LEFT JOIN BANK_GROUP BG ON BR.BGBK_ID = BG.BGBK_ID 	
    LEFT JOIN BANK_GROUP OP ON BG.OPBK_ID = OP.BGBK_ID 
) AS B ON A.BANKID = B.BRBK_ID 
WHERE  A.PCODE = '2101' --����N�� 
AND  B.OPBK_ID = '0040000' --�ާ@�� 
AND  B.BGBK_ID = '0040000' --�`��N�� 
AND  A.BANKID = '0040037' --����N��