--V4.0
SELECT
A.PCODE || '-' || COALESCE(A.EACH_TXN_NAME,'') PCODE,
VARCHAR_FORMAT(A.NEWTXDT, 'YYYY-MM-DD HH24:MI:SS') AS TXDT,
A.TXDATE, A.STAN,
A.SENDERBANKID || '-' || COALESCE((SELECT BRBK_NAME FROM BANK_BRANCH WHERE BRBK_ID=A.SENDERBANKID),'') SENDERBANKID, 
A.OUTBANKID || '-' || COALESCE((SELECT BRBK_NAME FROM BANK_BRANCH WHERE BRBK_ID=A.OUTBANKID),'') OUTBANKID, 
A.INBANKID || '-' || COALESCE((SELECT BRBK_NAME FROM BANK_BRANCH WHERE BRBK_ID=A.INBANKID),'') INBANKID, 
OUTACCTNO,INACCTNO,A.NEWTXAMT AS TXAMT,
A.TXID || '-' || (SELECT TXN_NAME FROM TXN_CODE WHERE TXN_ID = A.TXID) AS TXID,A.SENDERID 
FROM (
    SELECT * FROM (
        SELECT ROWNUMBER() OVER( ORDER BY TXDT asc) AS ROWNUMBER, PCODE, NEWTXDT, TXDATE, BIZDATE, STAN, OUTACCTNO, INACCTNO, NEWTXAMT, NEWRESULT,
        SENDERACQUIRE, SENDERHEAD, SENDERBANKID, OUTBANKID, INBANKID, TXID, SENDERID, EACH_TXN_NAME
        FROM VW_ONBLOCKTAB JOIN (
            SELECT EACH_TXN_ID, EACH_TXN_NAME
            FROM EACH_TXN_CODE
            WHERE BUSINESS_TYPE_ID = '2200'
        ) ON PCODE = EACH_TXN_ID
        WHERE RESULTSTATUS = 'P' AND SENDERSTATUS <> '1' AND  BIZDATE >= '20150428'  AND  BIZDATE <= '20150428'
    )
    WHERE ROWNUMBER >= 1 AND ROWNUMBER <= 10 
) AS A
ORDER BY TXDT asc

--V3.0
SELECT 
A.PCODE || '-' || COALESCE(C.EACH_TXN_NAME,'') PCODE, 
VARCHAR_FORMAT(A.NEWTXDT, 'YYYY-MM-DD HH24:MI:SS') AS TXDT, 
A.TXDATE, A.STAN, 
A.SENDERBANKID || '-' || COALESCE((SELECT BRBK_NAME FROM BANK_BRANCH WHERE BRBK_ID=A.SENDERBANKID),'') SENDERBANKID, 
A.OUTBANKID || '-' || COALESCE((SELECT BRBK_NAME FROM BANK_BRANCH WHERE BRBK_ID=A.OUTBANKID),'') OUTBANKID, 
A.INBANKID || '-' || COALESCE((SELECT BRBK_NAME FROM BANK_BRANCH WHERE BRBK_ID=A.INBANKID),'') INBANKID, 
OUTACCTNO,INACCTNO,A.NEWTXAMT AS TXAMT,A.TXID || '-' || (SELECT TXN_NAME FROM TXN_CODE WHERE TXN_ID = A.TXID) AS TXID,A.SENDERID 
FROM (
    SELECT * FROM (
        SELECT ROWNUMBER() OVER( ORDER BY TXDT asc) AS ROWNUMBER, PCODE, NEWTXDT, TXDATE, BIZDATE, STAN, OUTACCTNO, INACCTNO, NEWTXAMT, NEWRESULT,
        SENDERACQUIRE, SENDERHEAD, SENDERBANKID, OUTBANKID, INBANKID, TXID, SENDERID
        FROM VW_ONBLOCKTAB
        WHERE NEWRESULT = 'P' AND SENDERSTATUS <> '1' 
        AND  BIZDATE >= '20150317'  AND  BIZDATE <= '20150317'  
        AND  (SENDERACQUIRE = '9970018' OR OUTACQUIRE = '9970018' OR INACQUIRE = '9970018')  
        AND  (SENDERHEAD = '1610000' OR OUTHEAD = '1610000' OR INHEAD = '1610000') 
    ) WHERE ROWNUMBER >= 1 AND ROWNUMBER <= 10 
) AS A LEFT JOIN EACH_TXN_CODE C ON C.EACH_TXN_ID = A.PCODE
WHERE  C.BUSINESS_TYPE_ID = '2500'  
ORDER BY TXDT asc

--V2.0
SELECT
A.PCODE || '-' || COALESCE(C.EACH_TXN_NAME,'') PCODE, 
VARCHAR_FORMAT(A.NEWTXDT, 'YYYY-MM-DD HH24:MI:SS') AS TXDT, A.TXDATE, A.STAN, 
A.SENDERBANKID || '-' || COALESCE((SELECT BRBK_NAME FROM BANK_BRANCH WHERE BRBK_ID=A.SENDERBANKID),'') SENDERBANKID, 
A.OUTBANKID || '-' || COALESCE((SELECT BRBK_NAME FROM BANK_BRANCH WHERE BRBK_ID=A.OUTBANKID),'') OUTBANKID, 
A.INBANKID || '-' || COALESCE((SELECT BRBK_NAME FROM BANK_BRANCH WHERE BRBK_ID=A.INBANKID),'') INBANKID, 
OUTACCTNO,INACCTNO,A.NEWTXAMT AS TXAMT, (GETRESPDESC(A.TXDATE, A.STAN)) AS CONRESULTCODE
FROM (
        SELECT * FROM (
            SELECT ROWNUMBER() OVER() AS ROWNUMBER,
            PCODE, NEWTXDT, TXDATE, BIZDATE, STAN, OUTACCTNO, INACCTNO, NEWTXAMT, NEWRESULT,
            SENDERACQUIRE, SENDERHEAD, SENDERBANKID, OUTBANKID, INBANKID
            FROM VW_ONBLOCKTAB
            WHERE NEWRESULT = 'P' AND  BIZDATE >= '20141201'  AND  BIZDATE <= '20150305'
            AND  (SENDERACQUIRE = '9970018' OR OUTACQUIRE = '9970018' OR INACQUIRE = '9970018')  
            AND  (SENDERHEAD = '1610000' OR OUTHEAD = '1610000' OR INHEAD = '1610000')
        )
        WHERE ROWNUMBER >= 1 AND ROWNUMBER <= 10
) AS A LEFT JOIN EACH_TXN_CODE C ON C.EACH_TXN_ID = A.PCODE
WHERE C.BUSINESS_TYPE_ID = '2500'

--V1.0
SELECT
A.PCODE || '-' || COALESCE(C.EACH_TXN_NAME,'') PCODE, --������O
VARCHAR_FORMAT(A.NEWTXDT, 'YYYY-MM-DD HH24:MI:SS') AS TXDT, --������
A.STAN, --�t�ΰl�ܧǸ�
A.SENDERBANKID || COALESCE((SELECT BRBK_NAME FROM BANK_BRANCH WHERE BRBK_ID=A.SENDERBANKID),'') SENDERBANKID, --�o�ʦ�N��
A.OUTBANKID || COALESCE((SELECT BRBK_NAME FROM BANK_BRANCH WHERE BRBK_ID=A.OUTBANKID),'') OUTBANKID, --���ڦ�N��
A.INBANKID || COALESCE((SELECT BRBK_NAME FROM BANK_BRANCH WHERE BRBK_ID=A.INBANKID),'') INBANKID, --�J�b��N��
OUTACCTNO,INACCTNO,A.NEWTXAMT AS TXAMT, --���ڱb���B�J�b�b���B������B
COALESCE(D.ERR_DESC,'') CONRESULTCODE --�^��(��~)�N�X
FROM VW_ONBLOCKTAB A LEFT JOIN ONPENDINGTAB B ON B.OTXDATE=A.TXDATE AND B.OSTAN=A.STAN 
LEFT JOIN EACH_TXN_CODE C ON C.EACH_TXN_ID = A.PCODE 
LEFT JOIN TXN_ERROR_CODE D ON D.ERROR_ID = A.CONRESULTCODE 
WHERE  A.NEWRESULT = 'P' 
AND COALESCE(B.BIZDATE,'') = '' 
AND COALESCE(B.CLEARINGPHASE,'') = '' 
AND  A.BIZDATE >= '20150216' --��~��_ 
AND  A.BIZDATE <= '20150216' --��~�騴 
AND  (A.SENDERACQUIRE = '0040000' OR A.OUTACQUIRE = '0040000' OR A.INACQUIRE = '0040000') --�ާ@�� 
AND  (A.SENDERHEAD = '0040000' OR A.OUTHEAD = '0040000' OR A.INHEAD = '0040000') --�`��N�� 
AND  C.BUSINESS_TYPE_ID = '2100' --�~�����O