--V3.0
SELECT 
A.PCODE || '-' || COALESCE(A.EACH_TXN_NAME,'') AS PCODE, 
REPLACE('12-3','-','A' ),
VARCHAR_FORMAT((SELECT NEWTXDT FROM VW_ONBLOCKTAB B WHERE A.OTXDATE = B.TXDATE AND A.OSTAN = B.STAN),'YYYY-MM-DD HH24:MI:SS') AS TXDT, 
COALESCE(A.OSTAN,'') AS STAN, COALESCE(A.OTXDATE, '') AS TXDATE, 
A.SENDERBANKID || '-' || COALESCE((SELECT BRBK_NAME from BANK_BRANCH WHERE BRBK_ID = A.SENDERBANKID),'') AS SENDERBANKID, 
A.OUTBANKID || '-' || COALESCE((SELECT BRBK_NAME from BANK_BRANCH WHERE BRBK_ID = A.OUTBANKID),'') AS OUTBANKID,
A.INBANKID || '-' || COALESCE((SELECT BRBK_NAME from BANK_BRANCH WHERE BRBK_ID = A.INBANKID),'') AS INBANKID, 
A.OUTACCT, A.INACCT, (SELECT NEWTXAMT FROM VW_ONBLOCKTAB B WHERE A.OTXDATE = B.TXDATE AND A.OSTAN = B.STAN) AS TXAMT, 
(COALESCE(RESULTCODE, 'eACH')) AS CONRESULTCODE, A.OBIZDATE, A.OCLEARINGPHASE, 
(CASE A.RESULTCODE WHEN '01' THEN '失敗' ELSE '成功' END) AS RESULTCODE, '' AS ACCTCODE 
FROM (
     SELECT * FROM (
         SELECT ROWNUMBER() OVER(  ORDER BY PCODE,OSTAN asc    ) AS ROWNUMBER, PCODE, OTXDATE, OSTAN, SENDERBANKID, OUTBANKID, INBANKID, OUTACCT, INACCT, OBIZDATE, OCLEARINGPHASE,
         RESULTCODE, BIZDATE, CLEARINGPHASE, SENDERACQUIRE, SENDERHEAD, ETC.EACH_TXN_NAME
         FROM ONPENDINGTAB A LEFT JOIN EACH_TXN_CODE ETC ON A.PCODE = ETC.EACH_TXN_ID
         WHERE COALESCE(BIZDATE,'') <> '' AND COALESCE(CLEARINGPHASE,'') <> ''
         AND  BIZDATE >= '20150401'  AND  BIZDATE <= '20150430'  
         AND  (SENDERACQUIRE = '4530000' OR INACQUIRE = '4530000' OR OUTACQUIRE = '4530000')  
         AND  COALESCE(RESULTCODE,'00') = '00' 
         AND ETC.BUSINESS_TYPE_ID IN ('2200')
    )
    WHERE ROWNUMBER >= 1 AND ROWNUMBER <= 10 
) AS A 
ORDER BY PCODE,OSTAN asc

--V2.0
SELECT
A.PCODE || '-' || COALESCE(ETC.EACH_TXN_NAME,'') AS PCODE, 
REPLACE('12-3','-','A' ), 
VARCHAR_FORMAT((SELECT NEWTXDT FROM VW_ONBLOCKTAB B WHERE A.OTXDATE = B.TXDATE AND A.OSTAN = B.STAN),'YYYY-MM-DD HH24:MI:SS') AS TXDT, 
COALESCE(A.OSTAN,'') AS STAN, COALESCE(A.OTXDATE, '') AS TXDATE,
A.SENDERBANKID || '-' || COALESCE((SELECT BRBK_NAME from BANK_BRANCH WHERE BRBK_ID = A.SENDERBANKID),'') AS SENDERBANKID, 
A.OUTBANKID || '-' || COALESCE((SELECT BRBK_NAME from BANK_BRANCH WHERE BRBK_ID = A.OUTBANKID),'') AS OUTBANKID, 
A.INBANKID || '-' || COALESCE((SELECT BRBK_NAME from BANK_BRANCH WHERE BRBK_ID = A.INBANKID),'') AS INBANKID, 
A.OUTACCT, A.INACCT, 
(CASE (SELECT ACCTCODE FROM VW_ONBLOCKTAB B WHERE A.OTXDATE = B.TXDATE AND A.OSTAN = B.STAN) WHEN '0' 
THEN -(SELECT NEWTXAMT FROM VW_ONBLOCKTAB B WHERE A.OTXDATE = B.TXDATE AND A.OSTAN = B.STAN) ELSE 
(SELECT NEWTXAMT FROM VW_ONBLOCKTAB B WHERE A.OTXDATE = B.TXDATE AND A.OSTAN = B.STAN) END) AS TXAMT, 
(COALESCE(RESULTCODE, '')) AS CONRESULTCODE, A.OBIZDATE, A.OCLEARINGPHASE, 
(CASE A.RESULTCODE WHEN '01' THEN '失敗' ELSE '成功' END) AS RESULTCODE, 
(CASE (SELECT ACCTCODE FROM VW_ONBLOCKTAB B WHERE A.OTXDATE = B.TXDATE AND A.OSTAN = B.STAN) WHEN '0' THEN '調整' ELSE '一般' END) AS ACCTCODE
FROM (
    SELECT * FROM (
        SELECT ROWNUMBER() OVER( ORDER BY A.PCODE asc) AS ROWNUMBER,
        PCODE, OTXDATE, OSTAN, SENDERBANKID, OUTBANKID, INBANKID, OUTACCT, INACCT, OBIZDATE, OCLEARINGPHASE,
        RESULTCODE, BIZDATE, CLEARINGPHASE, SENDERACQUIRE, SENDERHEAD
        FROM ONPENDINGTAB A
        WHERE COALESCE(BIZDATE,'') <> '' AND COALESCE(CLEARINGPHASE,'') <> '' AND  BIZDATE= '20150304'
        AND  (SENDERACQUIRE = '4720000' OR INACQUIRE = '4720000' OR OUTACQUIRE = '4720000')
        AND  (SENDERHEAD = '4720000' OR INHEAD = '4720000' OR OUTHEAD = '4720000')
        AND  CLEARINGPHASE= '02' AND COALESCE(RESULTCODE,'00') = '00'
    )
    WHERE ROWNUMBER >= 1 AND ROWNUMBER <= 10
) AS A LEFT JOIN EACH_TXN_CODE ETC ON A.PCODE = ETC.EACH_TXN_ID
WHERE ETC.BUSINESS_TYPE_ID IN ('2100')

--V1.0
SELECT
A.PCODE || '-' || COALESCE(ETC.EACH_TXN_NAME,'') AS PCODE, --������O
REPLACE('12-3','-','A' ), VARCHAR_FORMAT(B.NEWTXDT,'YYYY-MM-DD HH24:MI:SS') AS TXDT, --������/�ɶ�
COALESCE(A.OSTAN,'') AS STAN, --�t�ΰl�ܧǸ�
A.SENDERBANKID || '-' || COALESCE((SELECT BRBK_NAME from BANK_BRANCH WHERE BRBK_ID = A.SENDERBANKID),'') AS SENDERBANKID, --�o�ʦ�
A.OUTBANKID || '-' || COALESCE((SELECT BRBK_NAME from BANK_BRANCH WHERE BRBK_ID = A.OUTBANKID),'') AS OUTBANKID, --���ڦ�
A.INBANKID || '-' || COALESCE((SELECT BRBK_NAME from BANK_BRANCH WHERE BRBK_ID = A.INBANKID),'') AS INBANKID, --�J�b��
A.OUTACCT, A.INACCT, B.NEWTXAMT AS TXAMT, --'���b�b��','�J�b�b��','������B'
(COALESCE(B.CONRESULTCODE,'') || '-' || (SELECT ERR_DESC FROM TXN_ERROR_CODE WHERE ERROR_ID = B.CONRESULTCODE)) AS CONRESULTCODE, --�^�ХN��
A.OBIZDATE, A.OCLEARINGPHASE, --'����~��','��M�ⶥ�q'
(CASE B.NEWRESULT WHEN 'R' THEN '����' WHEN 'A' THEN '���\' ELSE '������' END) AS RESULTCODE --�B�z���G
FROM ONPENDINGTAB A LEFT JOIN VW_ONBLOCKTAB B ON A.OTXDATE = B.TXDATE AND A.OSTAN = B.STAN 
LEFT JOIN EACH_TXN_CODE ETC ON A.PCODE = ETC.EACH_TXN_ID 
WHERE COALESCE(A.BIZDATE,'') <> '' AND COALESCE(A.CLEARINGPHASE,'') <> '' 
AND  A.BIZDATE= '20150216' --��~�� 
AND  (A.SENDERACQUIRE = '0040000' OR A.INACQUIRE = '0040000' OR A.OUTACQUIRE = '0040000') --�ާ@�� 
AND  (A.SENDERHEAD = '0040000' OR A.INHEAD = '0040000' OR A.OUTHEAD = '0040000') --�`��N�� 
AND  A.CLEARINGPHASE= '01' --�M�ⶥ�q 
AND  ETC.BUSINESS_TYPE_ID IN ('2100') --�~�����O