--V1.0
WITH TEMP AS (
    SELECT SENDERHEAD, OUTHEAD, INHEAD, RESULTSTATUS, TIMEOUTCODE, SENDERSTATUS, DT_REQ_1
    FROM VW_ONBLOCKTAB
    WHERE BIZDATE = '20150304' AND CLEARINGPHASE = '01' --AND SENDERACQUIRE = '4720000'
)

SELECT
A.BANKID || '-' || COALESCE((SELECT BGBK_NAME FROM BANK_GROUP WHERE BGBK_ID = A.BANKID),'') AS BANKID,
COALESCE((Select (case when MBSYSSTATUS='1' then '開機' when MBSYSSTATUS='2' then '押碼基碼同步' when MBSYSSTATUS='3' then '訊息通知' when MBSYSSTATUS='9' then '關機' else 'NA' end) From BANKSYSSTATUSTAB Where BGBK_ID=a.BANKID), '') MemBankSsySts, //--參加單位系統狀態
COALESCE((Select (case when MBAPSTATUS='1' then '簽到' when MBAPSTATUS='2' then '暫時簽退' when MBAPSTATUS='9' then '簽退'  else 'NA' end ) From BANKAPSTATUSTAB where BGBK_ID=a.BANKID and APID='2000'), '') MemBankAppSts,	//--參加單位應用系統狀態
(SELECT COUNT(*) FROM TEMP WHERE SENDERHEAD = A.BANKID AND RESULTSTATUS = 'A') FIRE_SUCCESS_COUNT,
(SELECT COUNT(*) FROM TEMP WHERE SENDERHEAD = A.BANKID AND RESULTSTATUS = 'R') FIRE_FAIL_COUNT,
(SELECT COUNT(*) FROM TEMP WHERE OUTHEAD = A.BANKID AND RESULTSTATUS = 'A') OUT_SUCCESS_COUNT,
(SELECT COUNT(*) FROM TEMP WHERE OUTHEAD = A.BANKID AND RESULTSTATUS = 'R') OUT_FAIL_COUNT, 
(SELECT COUNT(*) FROM TEMP WHERE INHEAD = A.BANKID AND RESULTSTATUS = 'A') IN_SUCCESS_COUNT, 
(SELECT COUNT(*) FROM TEMP WHERE INHEAD = A.BANKID AND RESULTSTATUS = 'R') IN_FAIL_COUNT,
(SELECT COUNT(*) FROM TEMP WHERE (SENDERHEAD = A.BANKID OR OUTHEAD = A.BANKID OR INHEAD = A.BANKID) AND LENGTH(TIMEOUTCODE) > 0) TIMEOUTCOUNT, //--逾時交易筆數
(SELECT COUNT(*) FROM TEMP WHERE (SENDERHEAD = A.BANKID OR OUTHEAD = A.BANKID OR INHEAD = A.BANKID) AND COALESCE(RESULTSTATUS,'P') = 'P') PENDTCOUNT_1, //--未完成筆數
(SELECT COUNT(*) FROM TEMP WHERE (SENDERHEAD = A.BANKID OR OUTHEAD = A.BANKID OR INHEAD = A.BANKID) AND RESULTSTATUS='P' AND SENDERSTATUS = '1') PENDTCOUNT_2, //--待處理筆數
(SELECT COUNT(*) FROM TEMP WHERE (SENDERHEAD = A.BANKID OR OUTHEAD = A.BANKID OR INHEAD = A.BANKID) AND COALESCE(DT_REQ_1,'') <> '' AND LENGTH(COALESCE(TIMEOUTCODE,'')) = 0) TOTALCOUNT, //--總筆數
COALESCE((Select REST_CR_LINE from CR_LINE where BANK_ID=a.BANKID), 0) REST_CR_LINE //--剩餘額度
FROM (
    SELECT SENDERHEAD AS BANKID FROM TEMP GROUP BY SENDERHEAD
    UNION
    SELECT OUTHEAD FROM TEMP GROUP BY OUTHEAD
    UNION
    SELECT INHEAD FROM TEMP GROUP BY INHEAD
) AS A