--V5.0
WITH TEMP AS (
    SELECT SENDERHEAD, OUTHEAD, INHEAD, SENDERBANKID, OUTBANKID, INBANKID, '1' AS ACCTCODE, PCODE, CLEARINGPHASE, NEWTXAMT FROM VW_ONBLOCKTAB
    WHERE (NEWRESULT = 'A' OR (NEWRESULT = 'P' AND SENDERSTATUS <> '1'))
    AND  BIZDATE = '20150811'  AND  (SENDERACQUIRE = '8160000' OR OUTACQUIRE = '8160000' OR INACQUIRE = '8160000')
    UNION ALL
    SELECT SENDERHEAD, OUTHEAD, INHEAD, SENDERBANKID, OUTBANKID, INBANKID, ACCTCODE, PCODE, NEWCLRPHASE, NEWTXAMT FROM VW_ONPENDING_EC
    WHERE  NEWBIZDATE = '20150811'  AND  (SENDERACQUIRE = '8160000' OR OUTACQUIRE = '8160000' OR INACQUIRE = '8160000') 
)
SELECT
A.BANKID || '-' || (SELECT BGBK_NAME FROM BANK_GROUP WHERE BGBK_ID = A.BANKID) AS BANKIDANDNAME, A.PCODE AS PCODEANDNAME, CLEARINGPHASE,
(SELECT COUNT(*) FROM TEMP WHERE COALESCE(ACCTCODE,'') <> '0' AND INHEAD = A.BANKID AND PCODE = A.PCODE AND CLEARINGPHASE = A.CLEARINGPHASE) AS RECVCNT,
COALESCE((SELECT SUM(NEWTXAMT) FROM TEMP WHERE COALESCE(ACCTCODE,'') <> '0' AND INHEAD = A.BANKID AND PCODE = A.PCODE AND CLEARINGPHASE = A.CLEARINGPHASE),0) AS RECVAMT, 
(SELECT COUNT(*) FROM TEMP WHERE COALESCE(ACCTCODE,'') <> '0' AND OUTHEAD = A.BANKID AND PCODE = A.PCODE AND CLEARINGPHASE = A.CLEARINGPHASE) AS PAYCNT, 
COALESCE((SELECT SUM(NEWTXAMT) FROM TEMP WHERE COALESCE(ACCTCODE,'') <> '0' AND OUTHEAD = A.BANKID AND PCODE = A.PCODE AND CLEARINGPHASE = A.CLEARINGPHASE),0) AS PAYAMT,
(SELECT COUNT(*) FROM TEMP WHERE COALESCE(ACCTCODE,'') = '0' AND OUTHEAD = A.BANKID AND PCODE = A.PCODE AND CLEARINGPHASE = A.CLEARINGPHASE) AS RVSRECVCNT, 
COALESCE((SELECT ABS(SUM(NEWTXAMT)) FROM TEMP WHERE COALESCE(ACCTCODE,'') = '0' AND OUTHEAD = A.BANKID AND PCODE = A.PCODE AND CLEARINGPHASE = A.CLEARINGPHASE),0) AS RVSRECVAMT,
(SELECT COUNT(*) FROM TEMP WHERE COALESCE(ACCTCODE,'') = '0' AND INHEAD = A.BANKID AND PCODE = A.PCODE AND CLEARINGPHASE = A.CLEARINGPHASE) AS RVSPAYCNT, 
COALESCE((SELECT ABS(SUM(NEWTXAMT)) FROM TEMP WHERE COALESCE(ACCTCODE,'') = '0' AND INHEAD = A.BANKID AND PCODE = A.PCODE AND CLEARINGPHASE = A.CLEARINGPHASE),0) AS RVSPAYAMT
FROM (
    SELECT * FROM (
        SELECT ROWNUMBER() OVER(ORDER BY BANKID asc) AS ROWNUMBER, GET_CUR_OPBKID(T.BANKID,'01040811',0) AS OPBKID, T.* FROM (
            SELECT SENDERHEAD AS BANKID, CLEARINGPHASE, PCODE FROM TEMP GROUP BY SENDERHEAD, CLEARINGPHASE, PCODE
            UNION
            SELECT OUTHEAD, CLEARINGPHASE, PCODE FROM TEMP GROUP BY OUTHEAD, CLEARINGPHASE, PCODE
            UNION
            SELECT INHEAD, CLEARINGPHASE, PCODE FROM TEMP GROUP BY INHEAD, CLEARINGPHASE, PCODE
        ) AS T
    ) WHERE ROWNUMBER >= 1 AND ROWNUMBER <= 10
) AS A
WHERE A.BANKID = '0040000'

--V4.0
WITH TEMP AS (
    SELECT SENDERHEAD, OUTHEAD, INHEAD, SENDERBANKID, OUTBANKID, INBANKID, '1' AS ACCTCODE, PCODE, CLEARINGPHASE, NEWTXAMT FROM VW_ONBLOCKTAB
    WHERE (NEWRESULT = 'A' OR (NEWRESULT = 'P' AND SENDERSTATUS <> '1'))
    AND  BIZDATE = '20150312'  AND  PCODE = '2501'
    AND  (SENDERACQUIRE = '9970018' OR OUTACQUIRE = '9970018' OR INACQUIRE = '9970018')  
    AND  (SENDERHEAD = '1610000' OR OUTHEAD = '1610000' OR INHEAD = '1610000')  
    AND  CLEARINGPHASE = '01'
    UNION ALL     
    SELECT SENDERHEAD, OUTHEAD, INHEAD, SENDERBANKID, OUTBANKID, INBANKID, ACCTCODE, PCODE, NEWCLRPHASE, NEWTXAMT 
    FROM VW_ONPENDING_EC     
    WHERE  NEWBIZDATE = '20150312'  AND  PCODE = '2501'  
    AND  (SENDERACQUIRE = '9970018' OR OUTACQUIRE = '9970018' OR INACQUIRE = '9970018')  
    AND  (SENDERHEAD = '1610000' OR OUTHEAD = '1610000' OR INHEAD = '1610000')  
    AND  NEWCLRPHASE = '01' 
)
SELECT
A.BANKID || '-' || (SELECT BGBK_NAME FROM BANK_GROUP WHERE BGBK_ID = A.BANKID) AS BANKIDANDNAME,
A.PCODE AS PCODEANDNAME, CLEARINGPHASE,
(SELECT COUNT(*) FROM TEMP WHERE COALESCE(ACCTCODE,'') <> '0' AND INHEAD = A.BANKID AND PCODE = A.PCODE AND CLEARINGPHASE = A.CLEARINGPHASE) AS RECVCNT,
COALESCE((SELECT SUM(NEWTXAMT) FROM TEMP WHERE COALESCE(ACCTCODE,'') <> '0' AND INHEAD = A.BANKID AND PCODE = A.PCODE AND CLEARINGPHASE = A.CLEARINGPHASE),0) AS RECVAMT,
(SELECT COUNT(*) FROM TEMP WHERE COALESCE(ACCTCODE,'') <> '0' AND OUTHEAD = A.BANKID AND PCODE = A.PCODE AND CLEARINGPHASE = A.CLEARINGPHASE) AS PAYCNT, 
COALESCE((SELECT SUM(NEWTXAMT) FROM TEMP WHERE COALESCE(ACCTCODE,'') <> '0' AND OUTHEAD = A.BANKID AND PCODE = A.PCODE AND CLEARINGPHASE = A.CLEARINGPHASE),0) AS PAYAMT,
(SELECT COUNT(*) FROM TEMP WHERE COALESCE(ACCTCODE,'') = '0' AND OUTHEAD = A.BANKID AND PCODE = A.PCODE AND CLEARINGPHASE = A.CLEARINGPHASE) AS RVSRECVCNT, 
COALESCE((SELECT ABS(SUM(NEWTXAMT)) FROM TEMP WHERE COALESCE(ACCTCODE,'') = '0' AND OUTHEAD = A.BANKID AND PCODE = A.PCODE AND CLEARINGPHASE = A.CLEARINGPHASE),0) AS RVSRECVAMT,
(SELECT COUNT(*) FROM TEMP WHERE COALESCE(ACCTCODE,'') = '0' AND INHEAD = A.BANKID AND PCODE = A.PCODE AND CLEARINGPHASE = A.CLEARINGPHASE) AS RVSPAYCNT, 
COALESCE((SELECT ABS(SUM(NEWTXAMT)) FROM TEMP WHERE COALESCE(ACCTCODE,'') = '0' AND INHEAD = A.BANKID AND PCODE = A.PCODE AND CLEARINGPHASE = A.CLEARINGPHASE),0) AS RVSPAYAMT
FROM (
    SELECT * FROM (
        SELECT ROWNUMBER() OVER(ORDER BY BANKID asc) AS ROWNUMBER, T.* FROM (
            SELECT SENDERHEAD AS BANKID, CLEARINGPHASE, PCODE FROM TEMP GROUP BY SENDERHEAD, CLEARINGPHASE, PCODE
            UNION
            SELECT OUTHEAD, CLEARINGPHASE, PCODE FROM TEMP GROUP BY OUTHEAD, CLEARINGPHASE, PCODE
            UNION
            SELECT INHEAD, CLEARINGPHASE, PCODE FROM TEMP GROUP BY INHEAD, CLEARINGPHASE, PCODE
        ) AS T
    ) WHERE ROWNUMBER >= 1 AND ROWNUMBER <= 10
) AS A LEFT JOIN (
	 SELECT DISTINCT BGBK_ID, OPBK_ID
     FROM BANK_OPBK
     WHERE OPBK_ID = '9970018' AND BGBK_ID = '1610000'
) AS B ON A.BANKID = B.BGBK_ID 
WHERE  B.OPBK_ID = '9970018'  AND  B.BGBK_ID = '1610000'
ORDER BY BANKIDANDNAME asc

--V3.0(到總行)
WITH TEMP AS (
    SELECT SENDERHEAD, OUTHEAD, INHEAD, SENDERBANKID, OUTBANKID, INBANKID, '1' AS ACCTCODE, PCODE, CLEARINGPHASE, NEWTXAMT FROM VW_ONBLOCKTAB
    WHERE (NEWRESULT = 'A' OR (NEWRESULT = 'P' AND SENDERSTATUS <> '1'))
    AND  BIZDATE = '20150312'  AND  PCODE = '2501'
    AND  (SENDERACQUIRE = '9970018' OR OUTACQUIRE = '9970018' OR INACQUIRE = '9970018')  
    AND  (SENDERHEAD = '1610000' OR OUTHEAD = '1610000' OR INHEAD = '1610000')  
    AND  CLEARINGPHASE = '01'
    UNION ALL     
    SELECT SENDERHEAD, OUTHEAD, INHEAD, SENDERBANKID, OUTBANKID, INBANKID, ACCTCODE, PCODE, NEWCLRPHASE, NEWTXAMT 
    FROM VW_ONPENDING_EC     
    WHERE  NEWBIZDATE = '20150312'  AND  PCODE = '2501'  
    AND  (SENDERACQUIRE = '9970018' OR OUTACQUIRE = '9970018' OR INACQUIRE = '9970018')  
    AND  (SENDERHEAD = '1610000' OR OUTHEAD = '1610000' OR INHEAD = '1610000')  
    AND  NEWCLRPHASE = '01' 
)
SELECT
A.BANKID || '-' || (SELECT BGBK_NAME FROM BANK_GROUP WHERE BGBK_ID = A.BANKID) AS BANKIDANDNAME,
A.PCODE AS PCODEANDNAME, CLEARINGPHASE,
(SELECT COUNT(*) FROM TEMP WHERE COALESCE(ACCTCODE,'') <> '0' AND INHEAD = A.BANKID AND PCODE = A.PCODE AND CLEARINGPHASE = A.CLEARINGPHASE) AS RECVCNT,
COALESCE((SELECT SUM(NEWTXAMT) FROM TEMP WHERE COALESCE(ACCTCODE,'') <> '0' AND INHEAD = A.BANKID AND PCODE = A.PCODE AND CLEARINGPHASE = A.CLEARINGPHASE),0) AS RECVAMT,
(SELECT COUNT(*) FROM TEMP WHERE COALESCE(ACCTCODE,'') <> '0' AND OUTHEAD = A.BANKID AND PCODE = A.PCODE AND CLEARINGPHASE = A.CLEARINGPHASE) AS PAYCNT, 
COALESCE((SELECT SUM(NEWTXAMT) FROM TEMP WHERE COALESCE(ACCTCODE,'') <> '0' AND OUTHEAD = A.BANKID AND PCODE = A.PCODE AND CLEARINGPHASE = A.CLEARINGPHASE),0) AS PAYAMT,
(SELECT COUNT(*) FROM TEMP WHERE COALESCE(ACCTCODE,'') = '0' AND OUTHEAD = A.BANKID AND PCODE = A.PCODE AND CLEARINGPHASE = A.CLEARINGPHASE) AS RVSRECVCNT, 
COALESCE((SELECT ABS(SUM(NEWTXAMT)) FROM TEMP WHERE COALESCE(ACCTCODE,'') = '0' AND OUTHEAD = A.BANKID AND PCODE = A.PCODE AND CLEARINGPHASE = A.CLEARINGPHASE),0) AS RVSRECVAMT,
(SELECT COUNT(*) FROM TEMP WHERE COALESCE(ACCTCODE,'') = '0' AND INHEAD = A.BANKID AND PCODE = A.PCODE AND CLEARINGPHASE = A.CLEARINGPHASE) AS RVSPAYCNT, 
COALESCE((SELECT ABS(SUM(NEWTXAMT)) FROM TEMP WHERE COALESCE(ACCTCODE,'') = '0' AND INHEAD = A.BANKID AND PCODE = A.PCODE AND CLEARINGPHASE = A.CLEARINGPHASE),0) AS RVSPAYAMT
FROM (
    SELECT * FROM (
        SELECT ROWNUMBER() OVER(ORDER BY BANKID asc) AS ROWNUMBER, T.* FROM (
            SELECT SENDERHEAD AS BANKID, CLEARINGPHASE, PCODE FROM TEMP GROUP BY SENDERHEAD, CLEARINGPHASE, PCODE
            UNION
            SELECT OUTHEAD, CLEARINGPHASE, PCODE FROM TEMP GROUP BY OUTHEAD, CLEARINGPHASE, PCODE
            UNION
            SELECT INHEAD, CLEARINGPHASE, PCODE FROM TEMP GROUP BY INHEAD, CLEARINGPHASE, PCODE
        ) AS T
    ) WHERE ROWNUMBER >= 1 AND ROWNUMBER <= 10
) AS A LEFT JOIN (
     SELECT BG.BGBK_ID, OP.OPBK_ID
     FROM BANK_GROUP AS BG JOIN BANK_GROUP AS OP ON BG.OPBK_ID = OP.BGBK_ID
     WHERE  OP.BGBK_ID = '9970018'  AND  BG.BGBK_ID = '1610000'
) AS B ON A.BANKID = B.BGBK_ID 
WHERE  B.OPBK_ID = '9970018'  AND  B.BGBK_ID = '1610000'
ORDER BY BANKIDANDNAME asc

--v2.0(細到分行)
WITH TEMP AS (
    SELECT SENDERBANKID, OUTBANKID, INBANKID, ACCTCODE, PCODE, CLEARINGPHASE, NEWTXAMT FROM VW_ONBLOCKTAB
    WHERE (NEWRESULT = 'A' OR (NEWRESULT = 'P' AND SENDERSTATUS <> '1'))
    AND  BIZDATE = '20150312'  AND  PCODE = '2501'
    AND  (SENDERACQUIRE = '9970018' OR OUTACQUIRE = '9970018' OR INACQUIRE = '9970018')  
    AND  (SENDERHEAD = '1610000' OR OUTHEAD = '1610000' OR INHEAD = '1610000')  
    AND  CLEARINGPHASE = '01'     
    UNION ALL     
    SELECT SENDERBANKID, OUTBANKID, INBANKID, ACCTCODE, PCODE, NEWCLRPHASE, NEWTXAMT 
    FROM VW_ONPENDING_EC     
    WHERE  NEWBIZDATE = '20150312'  AND  PCODE = '2501'  
    AND  (SENDERACQUIRE = '9970018' OR OUTACQUIRE = '9970018' OR INACQUIRE = '9970018')  
    AND  (SENDERHEAD = '1610000' OR OUTHEAD = '1610000' OR INHEAD = '1610000')  
    AND  NEWCLRPHASE = '01' 
) 
SELECT 
A.BANKID || '-' || (SELECT BRBK_NAME FROM BANK_BRANCH WHERE BRBK_ID = A.BANKID) AS BANKIDANDNAME, 
A.PCODE AS PCODEANDNAME, CLEARINGPHASE, 
(SELECT COUNT(*) FROM TEMP WHERE COALESCE(ACCTCODE,'') <> '0' AND INBANKID = A.BANKID AND PCODE = A.PCODE) AS RECVCNT, 
COALESCE((SELECT SUM(NEWTXAMT) FROM TEMP WHERE COALESCE(ACCTCODE,'') <> '0' AND INBANKID = A.BANKID AND PCODE = A.PCODE),0) AS RECVAMT, 
(SELECT COUNT(*) FROM TEMP WHERE COALESCE(ACCTCODE,'') <> '0' AND OUTBANKID = A.BANKID AND PCODE = A.PCODE) AS PAYCNT, 
COALESCE((SELECT SUM(NEWTXAMT) FROM TEMP WHERE COALESCE(ACCTCODE,'') <> '0' AND OUTBANKID = A.BANKID AND PCODE = A.PCODE),0) AS PAYAMT, 
(SELECT COUNT(*) FROM TEMP WHERE COALESCE(ACCTCODE,'') = '0' AND OUTBANKID = A.BANKID AND PCODE = A.PCODE) AS RVSRECVCNT, 
COALESCE((SELECT ABS(SUM(NEWTXAMT)) FROM TEMP WHERE COALESCE(ACCTCODE,'') = '0' AND OUTBANKID = A.BANKID AND PCODE = A.PCODE),0) AS RVSRECVAMT, 
(SELECT COUNT(*) FROM TEMP WHERE COALESCE(ACCTCODE,'') = '0' AND INBANKID = A.BANKID AND PCODE = A.PCODE) AS RVSPAYCNT, 
COALESCE((SELECT ABS(SUM(NEWTXAMT)) FROM TEMP WHERE COALESCE(ACCTCODE,'') = '0' AND INBANKID = A.BANKID AND PCODE = A.PCODE),0) AS RVSPAYAMT 
FROM (
     SELECT * FROM (
         SELECT ROWNUMBER() OVER( ORDER BY BANKID asc) AS ROWNUMBER, T.* FROM (
            SELECT SENDERBANKID AS BANKID, CLEARINGPHASE, PCODE FROM TEMP GROUP BY SENDERBANKID, CLEARINGPHASE, PCODE
            UNION             SELECT OUTBANKID, CLEARINGPHASE, PCODE FROM TEMP GROUP BY OUTBANKID, CLEARINGPHASE, PCODE
            UNION             SELECT INBANKID, CLEARINGPHASE, PCODE FROM TEMP GROUP BY INBANKID, CLEARINGPHASE, PCODE
         ) AS T
     ) WHERE ROWNUMBER >= 1 AND ROWNUMBER <= 10 
) AS A LEFT JOIN (
     SELECT BR.BRBK_ID, BG.BGBK_ID, OP.OPBK_ID
     FROM BANK_BRANCH BR LEFT JOIN BANK_GROUP BG ON BR.BGBK_ID = BG.BGBK_ID
     LEFT JOIN BANK_GROUP AS OP ON BG.OPBK_ID = OP.BGBK_ID
     WHERE  OP.BGBK_ID = '9970018'  AND  BG.BGBK_ID = '1610000' 
) AS B ON A.BANKID = B.BRBK_ID 
WHERE  B.OPBK_ID = '9970018'  AND  B.BGBK_ID = '1610000'  
ORDER BY BANKIDANDNAME asc

--V1.0
SELECT
A.BANKID || '-' || (SELECT BGBK_NAME FROM BANK_GROUP WHERE BGBK_ID=A.BANKID) BANKIDANDNAME, --�Ȧ�
A.PCODE || ( SELECT EACH_TXN_NAME FROM EACH_TXN_CODE WHERE EACH_TXN_ID=A.PCODE) PCODEANDNAME, --������O�W��
A.RECVCNT, A.RECVAMT, A.PAYCNT, A.PAYAMT, A.RVSRECVCNT, A.RVSRECVAMT, A.RVSPAYCNT, A.RVSPAYAMT --'��������','�������B','���I����','���I���B','�R��-��������','�R��-�������B','�R��-���I����','�R��-���I���B'
FROM ONCLEARINGTAB A LEFT JOIN (
    SELECT BG.BGBK_ID, OP.BGBK_ID AS OPBK_ID, OP.BGBK_NAME AS OPBK_NAME
    FROM BANK_GROUP BG LEFT JOIN BANK_GROUP OP ON BG.OPBK_ID = OP.BGBK_ID
) B ON A.BANKID = B.BGBK_ID
WHERE A.BIZDATE = '20150216' --��~�� 
AND  A.PCODE = '2101' --������O 
AND  A.BANKID = '0040000' --�`�� 
AND  A.CLEARINGPHASE = '01' --�M�ⶥ�q
AND  B.OPBK_ID = '0040000' --�ާ@��