--銀行分行檔
CREATE TABLE ADMINISTRATOR.BANK_BRANCH ( 
    BGBK_ID    	VARCHAR(7) NOT NULL DEFAULT '',
    BRBK_ID    	VARCHAR(7) NOT NULL DEFAULT '',
    BRBK_NAME  	VARCHAR(40) DEFAULT NULL,
    TCH_ID     	VARCHAR(2) DEFAULT NULL,
    ACTIVE_DATE	VARCHAR(10) DEFAULT NULL,
    STOP_DATE  	VARCHAR(10) DEFAULT NULL,
    CDATE      	DATE DEFAULT NULL,
    UDATE      	DATE DEFAULT NULL,
    CONSTRAINT PK_BANK_BRANCH PRIMARY KEY(BGBK_ID,BRBK_ID)
)
GO
COMMENT ON TABLE ADMINISTRATOR.BANK_BRANCH IS '銀行分行檔'
GO
COMMENT ON COLUMN ADMINISTRATOR.BANK_BRANCH.BGBK_ID IS '總行代號'
GO
COMMENT ON COLUMN ADMINISTRATOR.BANK_BRANCH.BRBK_ID IS '分行代號'
GO
COMMENT ON COLUMN ADMINISTRATOR.BANK_BRANCH.BRBK_NAME IS '分行名稱'
GO
COMMENT ON COLUMN ADMINISTRATOR.BANK_BRANCH.TCH_ID IS '交換所代號'
GO
COMMENT ON COLUMN ADMINISTRATOR.BANK_BRANCH.ACTIVE_DATE IS '啟用日期(民國:yyyy/MM/dd)'
GO
COMMENT ON COLUMN ADMINISTRATOR.BANK_BRANCH.STOP_DATE IS '停用日期(民國:yyyy/MM/dd)'
GO
COMMENT ON COLUMN ADMINISTRATOR.BANK_BRANCH.CDATE IS '建立日期'
GO
COMMENT ON COLUMN ADMINISTRATOR.BANK_BRANCH.UDATE IS '異動日期'
GO


--銀行總行檔

CREATE TABLE ADMINISTRATOR.BANK_GROUP ( 
    BGBK_ID        	VARCHAR(7) NOT NULL DEFAULT '',
    BGBK_NAME      	VARCHAR(40) DEFAULT NULL,
    BGBK_ATTR      	VARCHAR(1) DEFAULT NULL,
    CTBK_ACCT      	VARCHAR(4) DEFAULT NULL,
    TCH_ID         	VARCHAR(2) DEFAULT NULL,
    OPBK_ID        	VARCHAR(7) DEFAULT NULL,
    CTBK_ID        	VARCHAR(7) DEFAULT NULL,
    ACTIVE_DATE    	VARCHAR(10) DEFAULT NULL,
    STOP_DATE      	VARCHAR(10) DEFAULT NULL,
    SND_FEE_BRBK_ID	VARCHAR(7) DEFAULT NULL,
    OUT_FEE_BRBK_ID	VARCHAR(7) DEFAULT NULL,
    IN_FEE_BRBK_ID 	VARCHAR(7) DEFAULT NULL,
    EDDA_FLAG      	VARCHAR(1) DEFAULT NULL,
    CDATE          	DATE DEFAULT NULL,
    UDATE          	DATE DEFAULT NULL,
    CONSTRAINT PK_BANK_GROUP PRIMARY KEY(BGBK_ID)
)
GO
COMMENT ON TABLE ADMINISTRATOR.BANK_GROUP IS '銀行總行檔'
GO
COMMENT ON COLUMN ADMINISTRATOR.BANK_GROUP.BGBK_ID IS '總行代號'
GO
COMMENT ON COLUMN ADMINISTRATOR.BANK_GROUP.BGBK_NAME IS '總行名稱'
GO
COMMENT ON COLUMN ADMINISTRATOR.BANK_GROUP.BGBK_ATTR IS '銀行屬性'
GO
COMMENT ON COLUMN ADMINISTRATOR.BANK_GROUP.CTBK_ACCT IS '央行帳號'
GO
COMMENT ON COLUMN ADMINISTRATOR.BANK_GROUP.TCH_ID IS '交換所代號'
GO
COMMENT ON COLUMN ADMINISTRATOR.BANK_GROUP.OPBK_ID IS '操作行代號'
GO
COMMENT ON COLUMN ADMINISTRATOR.BANK_GROUP.CTBK_ID IS '清算行代號'
GO
COMMENT ON COLUMN ADMINISTRATOR.BANK_GROUP.ACTIVE_DATE IS '啟用日期(民國:yyyy/MM/dd)'
GO
COMMENT ON COLUMN ADMINISTRATOR.BANK_GROUP.STOP_DATE IS '停用日期(民國:yyyy/MM/dd)'
GO
COMMENT ON COLUMN ADMINISTRATOR.BANK_GROUP.SND_FEE_BRBK_ID IS '發動行手續費分行代號'
GO
COMMENT ON COLUMN ADMINISTRATOR.BANK_GROUP.OUT_FEE_BRBK_ID IS '扣款行手續費分行代號'
GO
COMMENT ON COLUMN ADMINISTRATOR.BANK_GROUP.IN_FEE_BRBK_ID IS '入帳行手續費分行代號'
GO
COMMENT ON COLUMN ADMINISTRATOR.BANK_GROUP.EDDA_FLAG IS '識別eDDA是否已抓取過'
GO
COMMENT ON COLUMN ADMINISTRATOR.BANK_GROUP.CDATE IS '建立日期'
GO
COMMENT ON COLUMN ADMINISTRATOR.BANK_GROUP.UDATE IS '異動日期'
GO

--銀行總行承作業務檔

CREATE TABLE ADMINISTRATOR.BANK_GROUP_BUSINESS ( 
    BGBK_ID         	VARCHAR(7) NOT NULL DEFAULT '',
    BUSINESS_TYPE_ID	VARCHAR(4) NOT NULL DEFAULT '',
    CDATE           	DATE DEFAULT NULL,
    UDATE           	DATE DEFAULT NULL,
    CONSTRAINT PK_BANK_GRP_BUSI PRIMARY KEY(BGBK_ID,BUSINESS_TYPE_ID)
)
GO
COMMENT ON TABLE ADMINISTRATOR.BANK_GROUP_BUSINESS IS '銀行總行承作業務檔'
GO
COMMENT ON COLUMN ADMINISTRATOR.BANK_GROUP_BUSINESS.BGBK_ID IS '總行代號'
GO
COMMENT ON COLUMN ADMINISTRATOR.BANK_GROUP_BUSINESS.BUSINESS_TYPE_ID IS '業務別代號'
GO
COMMENT ON COLUMN ADMINISTRATOR.BANK_GROUP_BUSINESS.CDATE IS '建立日期'
GO
COMMENT ON COLUMN ADMINISTRATOR.BANK_GROUP_BUSINESS.UDATE IS '異動日期'
GO


--業務類別檔
CREATE TABLE ADMINISTRATOR.BUSINESS_TYPE ( 
    BUSINESS_TYPE_ID  	VARCHAR(4) NOT NULL,
    BUSINESS_TYPE_NAME	VARCHAR(20),
    CDATE             	DATE,
    UDATE             	DATE,
    CONSTRAINT PK_BIZ_TYPE PRIMARY KEY(BUSINESS_TYPE_ID)
)
GO
COMMENT ON TABLE ADMINISTRATOR.BUSINESS_TYPE IS '業務類別檔'
GO
COMMENT ON COLUMN ADMINISTRATOR.BUSINESS_TYPE.BUSINESS_TYPE_ID IS '業務類別代號'
GO
COMMENT ON COLUMN ADMINISTRATOR.BUSINESS_TYPE.BUSINESS_TYPE_NAME IS '業務類別名稱'
GO
COMMENT ON COLUMN ADMINISTRATOR.BUSINESS_TYPE.CDATE IS '建立日期'
GO
COMMENT ON COLUMN ADMINISTRATOR.BUSINESS_TYPE.UDATE IS '異動日期'
GO

--代付發動者基本資料檔
CREATE TABLE ADMINISTRATOR.SC_COMPANY_PROFILE ( 
    COMPANY_ID       	VARCHAR(10) NOT NULL DEFAULT '',
    COMPANY_ABBR_NAME	VARCHAR(40) DEFAULT NULL,
    COMPANY_NAME     	VARCHAR(200) DEFAULT NULL,
    TXN_ID           	VARCHAR(3) NOT NULL DEFAULT '',
    SND_BRBK_ID      	VARCHAR(7) NOT NULL DEFAULT '',
    IPO_COMPANY_ID   	VARCHAR(6) DEFAULT NULL,
    PROFIT_ISSUE_DATE	VARCHAR(10) DEFAULT NULL,
    CDATE            	DATE DEFAULT NULL,
    UDATE            	DATE DEFAULT NULL,
    CONSTRAINT PK_SC_COMP_PRO PRIMARY KEY(COMPANY_ID,TXN_ID,SND_BRBK_ID)
)
GO
COMMENT ON TABLE ADMINISTRATOR.SC_COMPANY_PROFILE IS '代付發動者基本資料檔'
GO
COMMENT ON COLUMN ADMINISTRATOR.SC_COMPANY_PROFILE.COMPANY_ID IS '發動者統一編號'
GO
COMMENT ON COLUMN ADMINISTRATOR.SC_COMPANY_PROFILE.COMPANY_ABBR_NAME IS '發動者簡稱'
GO
COMMENT ON COLUMN ADMINISTRATOR.SC_COMPANY_PROFILE.COMPANY_NAME IS '發動者名稱'
GO
COMMENT ON COLUMN ADMINISTRATOR.SC_COMPANY_PROFILE.TXN_ID IS '交易代號'
GO
COMMENT ON COLUMN ADMINISTRATOR.SC_COMPANY_PROFILE.SND_BRBK_ID IS '發動分行代號'
GO
COMMENT ON COLUMN ADMINISTRATOR.SC_COMPANY_PROFILE.IPO_COMPANY_ID IS '上市上櫃公司代號'
GO
COMMENT ON COLUMN ADMINISTRATOR.SC_COMPANY_PROFILE.PROFIT_ISSUE_DATE IS '現金股息發放日期(民國:yyyy/MM/dd)'
GO
COMMENT ON COLUMN ADMINISTRATOR.SC_COMPANY_PROFILE.CDATE IS '建立日期'
GO
COMMENT ON COLUMN ADMINISTRATOR.SC_COMPANY_PROFILE.UDATE IS '異動日期'
GO


--代收發動者基本資料檔
CREATE TABLE ADMINISTRATOR.SD_COMPANY_PROFILE ( 
    COMPANY_ID       	VARCHAR(10) NOT NULL DEFAULT '',
    COMPANY_ABBR_NAME	VARCHAR(40) DEFAULT NULL,
    COMPANY_NAME     	VARCHAR(200) DEFAULT NULL,
    TXN_ID           	VARCHAR(3) NOT NULL DEFAULT '',
    SND_BRBK_ID      	VARCHAR(7) NOT NULL DEFAULT '',
    CONTACT_INFO     	VARCHAR(160) DEFAULT NULL,
    START_DATE       	VARCHAR(10) DEFAULT NULL,
    DISPATCH_DATE    	VARCHAR(10) DEFAULT NULL,
    USER_NO          	VARCHAR(100) DEFAULT NULL,
    CASE_NO          	VARCHAR(200) DEFAULT NULL,
    STOP_DATE        	VARCHAR(10) DEFAULT NULL,
    CDATE            	DATE DEFAULT NULL,
    UDATE            	DATE DEFAULT NULL,
    CONSTRAINT PK_SD_COMP_PRO PRIMARY KEY(COMPANY_ID,TXN_ID,SND_BRBK_ID)
)
GO
COMMENT ON TABLE ADMINISTRATOR.SD_COMPANY_PROFILE IS '代收發動者基本資料檔'
GO
COMMENT ON COLUMN ADMINISTRATOR.SD_COMPANY_PROFILE.COMPANY_ID IS '發動者統一編號'
GO
COMMENT ON COLUMN ADMINISTRATOR.SD_COMPANY_PROFILE.COMPANY_ABBR_NAME IS '發動者簡稱'
GO
COMMENT ON COLUMN ADMINISTRATOR.SD_COMPANY_PROFILE.COMPANY_NAME IS '發動者名稱'
GO
COMMENT ON COLUMN ADMINISTRATOR.SD_COMPANY_PROFILE.TXN_ID IS '交易代號'
GO
COMMENT ON COLUMN ADMINISTRATOR.SD_COMPANY_PROFILE.SND_BRBK_ID IS '發動分行代號'
GO
COMMENT ON COLUMN ADMINISTRATOR.SD_COMPANY_PROFILE.CONTACT_INFO IS '聯絡人資訊'
GO
COMMENT ON COLUMN ADMINISTRATOR.SD_COMPANY_PROFILE.START_DATE IS '開辦日期(民國:yyyy/MM/dd)'
GO
COMMENT ON COLUMN ADMINISTRATOR.SD_COMPANY_PROFILE.DISPATCH_DATE IS '發文日期(民國:yyyy/MM/dd)'
GO
COMMENT ON COLUMN ADMINISTRATOR.SD_COMPANY_PROFILE.USER_NO IS '用戶號碼'
GO
COMMENT ON COLUMN ADMINISTRATOR.SD_COMPANY_PROFILE.CASE_NO IS '文號'
GO
COMMENT ON COLUMN ADMINISTRATOR.SD_COMPANY_PROFILE.STOP_DATE IS '停用日期(民國:yyyy/MM/dd)'
GO
COMMENT ON COLUMN ADMINISTRATOR.SD_COMPANY_PROFILE.CDATE IS '建立日期'
GO
COMMENT ON COLUMN ADMINISTRATOR.SD_COMPANY_PROFILE.UDATE IS '異動日期'
GO


--交易代號檔
CREATE TABLE ADMINISTRATOR.TXN_CODE ( 
    TXN_ID  	VARCHAR(3) NOT NULL,
    TXN_NAME	VARCHAR(30),
    TXN_TYPE	VARCHAR(30),
    TXN_CHECK_TYPE VARCHAR(1),
    TXN_DESC	   VARCHAR(200),
    ACTIVE_DATE VARCHAR(8),
    MAX_TXN_AMT	DECIMAL(16,2),
    BUSINESS_TYPE_ID VARCHAR(4),
    CDATE             	DATE,
    UDATE             	DATE,
    CONSTRAINT PK_BIZ_TYPE PRIMARY KEY(TXN_ID)
)

GO
COMMENT ON TABLE ADMINISTRATOR.TXN_CODE IS '交易代號檔'
GO
COMMENT ON TABLE ADMINISTRATOR.TXN_CODE.TXN_ID IS '交易代號檔'
GO
COMMENT ON COLUMN ADMINISTRATOR.TXN_CODE.TXN_NAME IS '交易代號'
GO
COMMENT ON COLUMN ADMINISTRATOR.TXN_CODE.TXN_TYPE IS '交易項目'
GO
COMMENT ON COLUMN ADMINISTRATOR.TXN_CODE.TXN_CHECK_TYPE IS '入帳檢核統一編號'
GO
COMMENT ON COLUMN ADMINISTRATOR.TXN_CODE.DESC IS '交易說明'
GO
COMMENT ON COLUMN ADMINISTRATOR.TXN_CODE.ACTIVE_DATE IS '啟用日期'
GO
COMMENT ON COLUMN ADMINISTRATOR.TXN_CODE.MAX_TXN_AMT IS '金額上限'
GO
COMMENT ON COLUMN ADMINISTRATOR.TXN_CODE.BUSINESS_TYPE_ID IS '適用業務類別'
GO
COMMENT ON COLUMN ADMINISTRATOR.TXN_CODE.CDATE IS '建立日期'
GO
COMMENT ON COLUMN ADMINISTRATOR.TXN_CODE.UDATE IS '異動日期'

--交易退回天數檔
CREATE TABLE ADMINISTRATOR.RETURN_DAY ( 
	TXN_ID		VARCHAR(4)	NOT NULL	DEFAULT '',
	RETURN_DAY	INT,
	ACTIVE_DATE	VARCHAR(8)	DEFAULT NULL,
	CDATE		DATE,
	UDATE		DATE,
	CONSTRAINT PK_RETURN_DAY PRIMARY KEY(TXN_ID)
)
COMMENT ON TABLE ADMINISTRATOR.RETURN_DAY IS '交易退回天數檔';
COMMENT ON COLUMN ADMINISTRATOR.RETURN_DAY.TXN_ID IS '交易代號';
COMMENT ON COLUMN ADMINISTRATOR.RETURN_DAY.RETURN_DAY IS '退回天數';
COMMENT ON COLUMN ADMINISTRATOR.RETURN_DAY.ACTIVE_DATE IS '啟用日期';
COMMENT ON COLUMN ADMINISTRATOR.RETURN_DAY.CDATE IS '建立日期';
COMMENT ON COLUMN ADMINISTRATOR.RETURN_DAY.UDATE IS '異動日期';
