--V1.0  20150626
SELECT 
A.YYYYMM, (SELECT TCH_ID FROM BANK_BRANCH BR WHERE BR.BGBK_ID = A.BGBK_ID AND BR.BRBK_ID = A.BRBK_ID) AS TCH_ID,  
A.BRBK_ID, A.FEE_CODE, (CASE WHEN A.AMT < 0 THEN '-' ELSE '+' END) AS SIGN,  
RIGHT(REPEAT('0',14) || REPLACE(VARCHAR(DECIMAL((  ROUND(DECIMAL((CASE WHEN A.AMT < 0 THEN -A.AMT ELSE A.AMT END), 14, 2), 0)  ), 14, 0)),'.',''), 14) AS AMT,  
'                ' AS BLANK  
FROM ( 
	SELECT SUBSTR(TRANS_DATE(YYYYMM || '01','T',''), 1, 6) AS YYYYMM, BR.BGBK_ID, RPC.BRBK_ID, '507' AS FEE_CODE, 
	SUM(AMT)+SUM(RVSAMT)+COALESCE((SELECT FEE FROM BRBK_FEE_ADJ BFA WHERE VARCHAR(INT(BFA.YYYYMM)+191100) = RPC.YYYYMM AND BFA.BRBK_ID = RPC.BRBK_ID),0) AS AMT 
	FROM EACHUSER.RPCLEARFEETAB RPC LEFT JOIN BANK_BRANCH BR ON RPC.BRBK_ID = BR.BRBK_ID 
	WHERE YYYYMM = '201505' 
	GROUP BY YYYYMM, BR.BGBK_ID, RPC.BRBK_ID 
) AS A ORDER BY A.BRBK_ID  


--V2.0  20150627
WITH TEMP AS ( 
    SELECT 	
    RPC.BRBK_ID,
	SUM(AMT)+SUM(RVSAMT)+COALESCE(
	(SELECT FEE FROM BRBK_FEE_ADJ BFA WHERE VARCHAR(INT(BFA.YYYYMM)+191100) = RPC.YYYYMM AND BFA.BRBK_ID = RPC.BRBK_ID),0) 
	AS AMT 
	FROM EACHUSER.RPCLEARFEETAB RPC LEFT JOIN BANK_BRANCH BR ON RPC.BRBK_ID = BR.BRBK_ID 
	WHERE YYYYMM = '201505' 
	GROUP BY YYYYMM, BR.BGBK_ID, RPC.BRBK_ID 
	)

SELECT 
SUBSTR(TRANS_DATE('201505' || '01','T',''), 1, 6) AS YYYYMM, 
COALESCE((SELECT TCH_ID FROM BANK_BRANCH WHERE BRBK_ID = A.BRBK_ID),'  ') AS TCH_ID,
A.BRBK_ID,
'507' AS FEE_CODE,
(CASE WHEN (SELECT AMT FROM TEMP WHERE BRBK_ID=A.BRBK_ID) < 0 THEN '-' WHEN (SELECT AMT FROM TEMP WHERE BRBK_ID=A.BRBK_ID) > 0 THEN '+'   
WHEN(SELECT FEE FROM BRBK_FEE_ADJ WHERE YYYYMM='010405' AND BRBK_ID=A.BRBK_ID) < 0 THEN '-' ELSE '+' END) AS SIGN,
COALESCE( ( 
    SELECT ( RIGHT(REPEAT('0',14) || REPLACE(VARCHAR(DECIMAL((  ROUND(DECIMAL((CASE WHEN AMT < 0 THEN -AMT ELSE AMT END), 14, 2), 0)  ), 14, 0)),'.',''), 14) ) AS AMT  
    FROM TEMP WHERE BRBK_ID=A.BRBK_ID   
),( SELECT ( RIGHT(REPEAT('0',14) || REPLACE(VARCHAR(DECIMAL((  ROUND(DECIMAL((CASE WHEN FEE < 0 THEN -FEE ELSE FEE END), 14, 2), 0)  ), 14, 0)),'.',''), 14) ) AS FEE 
    FROM BRBK_FEE_ADJ WHERE YYYYMM='010405' AND BRBK_ID=A.BRBK_ID) ) AS AMT,
'                ' AS BLANK     
FROM 
(SELECT BRBK_ID FROM  RPCLEARFEETAB WHERE YYYYMM='201505' UNION  SELECT BRBK_ID  FROM  BRBK_FEE_ADJ WHERE  YYYYMM='010405') AS A


--V2.1  20150714 (過濾票交 BRBK_ID<>'0188888' )
WITH TEMP AS ( 
    SELECT 	
    RPC.BRBK_ID,
	SUM(AMT)+SUM(RVSAMT)+COALESCE(
	(SELECT FEE FROM BRBK_FEE_ADJ BFA WHERE VARCHAR(INT(BFA.YYYYMM)+191100) = RPC.YYYYMM AND BFA.BRBK_ID = RPC.BRBK_ID),0) 
	AS AMT 
	FROM EACHUSER.RPCLEARFEETAB RPC LEFT JOIN BANK_BRANCH BR ON RPC.BRBK_ID = BR.BRBK_ID 
	WHERE YYYYMM = '201505' 
	GROUP BY YYYYMM, BR.BGBK_ID, RPC.BRBK_ID 
	)

SELECT 
SUBSTR(TRANS_DATE('201505' || '01','T',''), 1, 6) AS YYYYMM, 
COALESCE((SELECT TCH_ID FROM BANK_BRANCH WHERE BRBK_ID = A.BRBK_ID),'  ') AS TCH_ID,
A.BRBK_ID,
'507' AS FEE_CODE,
(CASE WHEN (SELECT AMT FROM TEMP WHERE BRBK_ID=A.BRBK_ID) < 0 THEN '-' WHEN (SELECT AMT FROM TEMP WHERE BRBK_ID=A.BRBK_ID) > 0 THEN '+'   
WHEN(SELECT FEE FROM BRBK_FEE_ADJ WHERE YYYYMM='010405' AND BRBK_ID=A.BRBK_ID) < 0 THEN '-' ELSE '+' END) AS SIGN,
COALESCE( ( 
    SELECT ( RIGHT(REPEAT('0',14) || REPLACE(VARCHAR(DECIMAL((  ROUND(DECIMAL((CASE WHEN AMT < 0 THEN -AMT ELSE AMT END), 14, 2), 0)  ), 14, 0)),'.',''), 14) ) AS AMT  
    FROM TEMP WHERE BRBK_ID=A.BRBK_ID   
),( SELECT ( RIGHT(REPEAT('0',14) || REPLACE(VARCHAR(DECIMAL((  ROUND(DECIMAL((CASE WHEN FEE < 0 THEN -FEE ELSE FEE END), 14, 2), 0)  ), 14, 0)),'.',''), 14) ) AS FEE 
    FROM BRBK_FEE_ADJ WHERE YYYYMM='010405' AND BRBK_ID=A.BRBK_ID) ) AS AMT,
'                ' AS BLANK     
FROM 
(SELECT BRBK_ID FROM  RPCLEARFEETAB WHERE YYYYMM='201505' AND BRBK_ID<>'0188888'  UNION  SELECT BRBK_ID  FROM  BRBK_FEE_ADJ WHERE  YYYYMM='010405' AND BRBK_ID<>'0188888') AS A 

