--手動抓取總行檔的清算行至額度檔  D4額度為2百萬
INSERT INTO EACHUSER.CR_LINE(BANK_ID, BASIC_CR_LINE, REST_CR_LINE, USER_ID, CDATE, UDATE) 
    VALUES('', 2000000, 2000000, '', '2015-3-18', '')
SELECT DISTINCT  CTBK_ID AS BANK_ID
FROM EACHUSER.BANK_GROUP
GO


--抓取總行ID=操作行ID 資料塞入BANKAPSTATUSTAB
INSERT INTO EACHUSER.BANKAPSTATUSTAB(BGBK_ID, APID) VALUES('', '2000')
SELECT DISTINCT  BGBK_ID
FROM EACHUSER.BANK_GROUP 
WHERE BGBK_ID = OPBK_ID
GO
--抓取總行ID=操作行ID 資料塞入BANKSYSSTATUSTAB
INSERT INTO EACHUSER.BANKSYSSTATUSTAB(BGBK_ID, UNSYNCCNT01, UNSYNCCNT02, UNSYNCCNT03, UNSYNCCNT04) 
    VALUES('',  0, 0, 0, 0)
SELECT DISTINCT  BGBK_ID
FROM EACHUSER.BANK_GROUP 
WHERE BGBK_ID = OPBK_ID
GO
